### ISSUE TITLE
 [Feature Request] Web app Volumes should be reflected on the client system

### ISSUE THREAD

**Issue by zi0Black** [FilenCloudDienste/filen-desktop#10]
Hello,
I would like to propose a new feature.

Volumes created via the web application could be replicated on desktop clients as virtual disks (like Google Drive does), I think it would make management for users much easier.

Thank you.

![image](https://user-images.githubusercontent.com/13380579/136445999-97704cd4-230a-4c15-b4df-d9aecfe24416.png)

**Comment by ashutoshsaboo** [comment]
+1 on this request as well, this would be really an awesome feature to have! The UX would become so much better on desktop. :)

**Comment by EdwardLangdon** [comment]
I think this will no long be done as all the Cloud Drives are merged into a single folder.

**Comment by EdwardLangdon** [comment]
> I don't think this is a problem, it can just show the setup sync locations

A better replacement would be subfolders in that volume or like MegaSync in Sidebar > Subfolders.

**Comment by Redre1l** [comment]
> > I don't think this is a problem, it can just show the setup sync locations
> 
> A better replacement would be subfolders in that volume or like MegaSync in Sidebar > Subfolders.

Yeah i dont like mounted drives like this but it can work.
I like the sidebar thing though.

**Comment by EdwardLangdon** [comment]
Sidebar is effective than Volumes.

**Comment by Dwynr** [comment]
Update: We are working on a CLI tool behind the scenes which will make it possible to host your own WebDAV gateway. WebDAV can be integrated into all major platforms. It can be mounted as a filesystem. The CLI will also be integrated into the desktop client. Closing for now.

**Comment by DanielProg39** [comment]
Idk how relevant is it to WebDAV, Rclone or anything, but pCloud and Icedrive allow to mount their cloud drives using literally one button and pleasant user interface. So I think that there should be at least a button in the app allowing to add Filen drive to your system. Otherwise non-techy users would be confused.
Cli client is absolutely a must and the Rust programming language is the best option out there for cli tools, I love it and it's great that you're using it. But together with that, maybe later, drive mounting feature should be added to standard Filen app interface

**Comment by msrumon** [comment]
> 

Yes, literally that. Having the storage mounted as network drive is 1000x better and efficient than just a mere sync folder. This is why I'm still actively looking for *Google Drive* alternative with E2EE built right in. If **Filen** is able to pull this off, I'll jump right in.

**Comment by msrumon** [comment]
> Idk how relevant is it to WebDAV, Rclone or anything, but pCloud and Icedrive allow to mount their cloud drives using literally one button and pleasant user interface. So I think that there should be at least a button in the app allowing to add Filen drive to your system. Otherwise non-techy users would be confused. Cli client is absolutely a must and the Rust programming language is the best option out there for cli tools, I love it and it's great that you're using it. But together with that, maybe later, drive mounting feature should be added to standard Filen app interface

Yes, literally that. Having the storage mounted as network drive is 1000x better and efficient than just a mere sync folder. This is why I'm still actively looking for *Google Drive* alternative with E2EE built right in. If **Filen** is able to pull this off, I'll jump right in.
