### ISSUE TITLE
Synchronizations Cannot Be Renamed & Synchronization Name Display is Truncated

### ISSUE THREAD

**Issue by SEC-D-E** [FilenCloudDienste/filen-desktop#100]
#### **Issue 1: Synchronizations Cannot Be Renamed**
- **Description**: Once a synchronization folder is created, it is not possible to rename it. The option to modify the synchronization name is missing or inaccessible within the application's interface. 
- **Impact**: This limitation reduces flexibility, especially when users want to adjust naming conventions for better organization.
- **Expected Behavior**: Users should be able to rename synchronization folders post-creation via an "Edit" or "Rename" option in the interface.

---

#### **Issue 2: Synchronization Name Display is Truncated**
- **Description**: The synchronization name is truncated due to a vertical divider in the application window. Even when resizing the window horizontally, the truncation persists, as the divider cannot be moved to allocate more space for the name.
- **Impact**: Users cannot fully view synchronization names, especially for longer entries, leading to reduced clarity and usability.
- **Expected Behavior**: The vertical divider should be adjustable to allow users to expand the area displaying the synchronization name. Alternatively, text wrapping or a tooltip displaying the full name on hover could resolve this issue.

---

### Suggestions:
- Enable renaming functionality for synchronization folders.
- Allow the vertical divider to be draggable or implement an alternative method to display full synchronization names.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/df3e651fdb977095fd687c346a216d17cc7eb313
