### ISSUE TITLE
WebDav and S3 cannot be accessed on MacOS Sequoia (15.x)

### ISSUE THREAD

**Issue by 21Kingshill** [FilenCloudDienste/filen-desktop#101]
MacOS 15.x / Filen Drive has been set up and works (Full disk access is granted):

![ScreenFloat Bildschirmfoto von Filen am 20_11_2024, 22_08_07](https://github.com/user-attachments/assets/bd3a81fe-f427-4a2a-98b6-302cfd9dce81)

When starting S3 Service as shown here:

![ScreenFloat Bildschirmfoto von Filen am 20_11_2024, 22_09_39](https://github.com/user-attachments/assets/ba83caad-d150-4747-b0fa-80c448d6b10e)

it's possible to to access the URL and enter the given credentials first, but it ends up with error "Required headers are missing"

Similar on WebDav: After login, the error "/ HTTP/1.1 404 NOT FOUND" is shown.

- OS: MacOS Sequoia
- Hardware configuration MBP M4

**Additional context**
Not sure, if this is an expected behavior: It's not possible to use any backup tools (arq / Kopia / Duplicacy) on the file drive directly. Lot's of errors and only are could finish the backup but was not able to read the stored items anymore (no restore possible).

**Comment by Dwynr** [comment]
Please make sure you are using an appropriate client that talks the WebDAV our S3 protocl (and make sure the endpoint, authentication method, port and credentials are correct). Simply accessing the URL in a browser or w/e won't work.

**Comment by 21Kingshill** [comment]
My mistake. I wanted to add the error when connecting to S3 by using proper S3 compliant clients

A) S3 with arq Backup:

1.  S3 (HTTPS): Error, invalid certificate
2.  S3 (HTTP): GET http://127.0.0.1:8080/arq/?prefix=37D52574-88B8-4C83-BF41-F909B5BE9F45/&delimiter=/&max-keys=500: The requested method is not implemented.

Are works reliable with other S3 spaces.

B) KopiaUI
1. S3 (HTTPS) and 
2. S3 (HTTP): Connect Error: INTERNAL: internal server error: unable to create client: Endpoint url cannot have fully qualified paths.
3. 
![ScreenFloat Bildschirmfoto von KopiaUI am 21_11_2024, 08_39_44](https://github.com/user-attachments/assets/0276477a-213f-47c9-be36-734c6134dc01)

C) Webdav using Kopia
HTTPS or HTTP
Connect Error: INTERNAL: internal server error: unable to complete GetBlob(kopia.repository,0,-1) despite 10 retries: error determining sharded path: error getting sharding parameters for storage: ReadStream .shards: Get "https://127.0.0.1:1900/.shards": tls: failed to verify certificate: x509: certificate signed by unknown authority


Does this help to investigate?

Seconds questions. Is a direct backup with 3rd party tools to to the filen drive intended (should that work or not)

**Comment by Dwynr** [comment]
A):

1: The local S3 server uses a self signed certificate. Set your client to ignore self signed certificates or disable HTTPS if you are only using it locally
2: There is only one bucket called "filen". You are trying to access a bucket named "arq".

B):

1. See A1.
2. You need to use s3ForcePathStyle and set the storage region to "filen" + bucket to "filen".

C): See A1.

I'd suggest to read our documentation about S3 and WebDAV at https://docs.filen.io/docs/cli/webdav-and-s3-server as this is a user error.

**Comment by 21Kingshill** [comment]
Thanks for the explanation. Agree, it was an user error, but since I'm a user not a developer I didn't search for a CLI documentation when setting up a standard user GUI.
