### ISSUE TITLE
Browse & Access Files On Cloud

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#101]
Essentially having the web client being available in the desktop client, to allow the user to browse their files on the cloud, rename files and folders, upload files, upload folders, create files, etc.

This will be a more secure option for those who use Filen for cold storage and can use the desktop client which will be more secure than using the web client for cold storage.

**Comment by Dwynr** [comment]
The desktop client, app and website file manager all communicate with the same API. Not sure what you mean by "cold" storage. Embedding the website into the desktop client will not make it more secure. It is already secure.

**Comment by DanielProg39** [comment]
> The desktop client, app and website file manager all communicate with the same API. Not sure what you mean by "cold" storage. Embedding the website into the desktop client will not make it more secure. It is already secure.

I think that by "cold" storage he meant that he doesn't use it for syncing, just to store files he chooses. And he means that it'll be more convenient to use desktop app not only for syncing, but to use it as a full-featured cloud storage browser so he would be able to manually download or upload files or make other changes in the cloud as in the web app.
I think that the best way to do that is to implement cloud drive mounting

**Comment by trymeouteh** [comment]
> I think that by "cold" storage he meant that he doesn't use it for syncing, just to store files he chooses. And he means that it'll be more convenient to use desktop app not only for syncing, but to use it as a full-featured cloud storage browser so he would be able to manually download or upload files or make other changes in the cloud as in the web app.

That is what I meant
