### ISSUE TITLE
VPN Kill Switch

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#102]
I recently discovered that qBittorrent essentially has a [VPN Kill Switch feature](https://www.ghacks.net/2016/03/23/qbittorrent-block-transfers-vpn-disconnect/) built into the client which will kill its connection if it detects your VPN has disconnected. VPN kill switches from VPN clients for the desktop are not fully reliable as they can often fail and you can still connect to the internet with a unencrypted connection with your IP exposed.

I would like to purpose adding this feature in Filen settings on desktop. This way if your VPN disconnects, Filen client will also lose internet access too. There has been many times my VPN disconnects without me knowing while I was syncing data to my cloud.

Some people would have bought a Filen account privately using crypto and a private email using a VPN and would like to keep their cloud storage account private. I am sure these users would like this feature quite a bit.

**Comment by doubletimedan** [comment]
It's a good idea but it feels like this is more of your VPN providers problem for not fixing it then filen having to add that in (also In my opinion I don't think any cloud provider cares what ip you connect from as long as it isn't banned)

**Comment by EdwardLangdon** [comment]
@trymeouteh Just enable Permanent Kill Switch. So, No data is sent unless there is a connection to the VPN server.

**Comment by Dwynr** [comment]
> It's a good idea but it feels like this is more of your VPN providers problem for not fixing it then filen having to add that in (also In my opinion I don't think any cloud provider cares what ip you connect from as long as it isn't banned)

I agree. Your VPN client should be responsible for this.
