### ISSUE TITLE
Start in system tray, and default close button action should minimize to tray instead of exiting.

### ISSUE THREAD

**Issue by uncharted-user** [FilenCloudDienste/filen-desktop#102]
**Is your feature request related to a problem? Please describe.**
Thank you for the quick implementation of minimizing to tray. Although, the solution is working properly but kind of unconventional.

**Describe the solution you'd like**
It would have been better if the app would start to system tray instead of full window. The default close shall close the window, but still running the app at tray. Finally, quitting the app from the tray would stop the app.

**Describe alternatives you've considered**
Currently, no similar alternative is available.

**Comment by paololunghi** [comment]
I agree, the behavior described as desired is more conventional.
In any case, thank you for the prompt implementation of the feature!

**Comment by dermitdemdino** [comment]
The new desktop app (I use it on Linux) is great. If it would start minimized, it would be perfect!

**Comment by RodsonMatos** [comment]
> They also wrote the following on https://blog.filen.io/how-to-desktop-client/ :
> 
> > **Minimize to tray**
> > Select whether the client should be closed completely when closing via the X, or whether it should be minimized to the background.

as I saw on reddit, only windows users related this feature.

**Comment by uncharted-user** [comment]
> as I saw on reddit, only windows users related this feature.

It is not a conventional way.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-desktop/commit/a6ddcf68596b20695a766d1c907fe5cbcd6cbba5
https://github.com/FilenCloudDienste/filen-web/commit/3b5b26aa3a1e47f38b8bcf482f59570b741a6d14
