### ISSUE TITLE
Dark Mode and Light Mode settings change back to "System" when application is closed and opened again (macOS 15.1)

### ISSUE THREAD

**Issue by Dummbeudl** [FilenCloudDienste/filen-desktop#103]
**Describe the bug**
My system is on light mode and when I want the application to appear on dark mode, the setting resets after closing the Filen app

**Expected behavior**
Dark mode should be kept after the program is closed and opened up again

**System:** 
Macbook Air M1 2020, 8/265GB

**Comment by Stolenbanana** [comment]
Same problem but reversed on Linux, I have changed it to  dark mode and every time I restart it goes back to "System" and is light, even though my default system theme is dark.

**Comment by paololunghi** [comment]
I confirm it happens also in the linux version (Ubuntu 22.04).

**Comment by Dwynr** [comment]
Should be fixed via https://github.com/FilenCloudDienste/filen-web/commit/db225fcdb4672a78fc83ca5bb7a2aacee7bdf403.
