### ISSUE TITLE
Longer File/Directory Path Limit

### ISSUE THREAD

**Issue by Ed-V** [FilenCloudDienste/filen-desktop#104]
**Is your feature request related to a problem? Please describe.**
Sometime I run into files that are fine on Google Drive/Windows that runs into filename/directory too long in filen

**Describe the solution you'd like**
Increase the filename/directory path limit so that it can at least match what's on Google Drive/Windows

**Describe alternatives you've considered**
None, it's really inconvenient to have to rename the files. Sometimes files are generated by programs and is not feasible to rename. 

**Additional context**
None

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-sync/commit/7e43495db2227a66518cd12180089f74b0dd9284
