### ISSUE TITLE
Selective Sync doesn't work and download multiple folders

### ISSUE THREAD

**Issue by reyman** [FilenCloudDienste/filen-desktop#105]
I have a problem with selective sync, the folder selected is well synced, but all folders into the same folder of selective sync are already synced ... 

For example if if sync **"D:/PDF"** with **"CloudDrive/pdf_inbox"** filen folder. 
On my local desktop disk, after sync, **"D:/PDF**" contain all the others folder of CloudDrive... 

NOT very selective .

I use v 2.0.5 on windows 10.

**Comment by Dwynr** [comment]
Sorry but I don't really get what you are trying to say. I need a detailed reproduction report, otherwise I can't really help you.
