### ISSUE TITLE
Add support for AVIF file format

### ISSUE THREAD

**Issue by stephanschindel** [FilenCloudDienste/filen-desktop#105]
**Is your feature request related to a problem? Please describe.**
AVIF files cannot be opened (decrypted and displayed, thumbnail support) in the app.

**Describe the solution you'd like**
AVIF is besides JPEG XL one of the upcoming image formats and it makes sense to add support for it.

**Describe alternatives you've considered**
Use good old JPEG :).

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
