### ISSUE TITLE
Linux: Ignore symbolic links

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#106]
I am syncing a directory to the cloud which does contain some symbolic links which are symbolic links to files and folders. However Filen will sync these items with the cloud and because of this, the sync always get buggy with error messages and syncing take way longer going through these symbolic links.

Please have Filen on Linux ignore symbolic links when syncing to prevent any issues and to have a smoother syncing experience.

**Comment by RasheedAZ** [comment]
I have same issue. When there's a link to another folder, even on another drive, Filen will download that one also...

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-desktop/blob/master/src/renderer/lib/fs/local/fs-local.ts#L365

Symlinks are ignored by default. If it's a hardlink then it can't tell the difference programmatically and will include it.

**Comment by rauldipeas** [comment]
I'm running Filen on Kubuntu 22.04, and it's not ignoring symlinks, instead it's trying to send all content inside symlinks folders to the cloud.

There's an `ignore` file where I can set some paths to not sync?
