### ISSUE TITLE
Virtual Files / Files On-Demand

### ISSUE THREAD

**Issue by szapp** [FilenCloudDienste/filen-desktop#106]
Introduce a **"Virtual Files"** or **"Files On-Demand"** feature using the Windows Cloud Files API to provide users with seamless access to their cloud files without consuming local storage with and without internet access. This feature has become a standard in cloud storage solutions and will enhance user satisfaction, retention, and competitiveness.

# Current state
Currently, users must either download files entirely to their local storage, rely on a constant internet connection when using the new network drive feature, or manage selective sync manually, leading to:
- **Wasted local storage space** for large files - or **no file access without internet** (network drive).
- **Complex and continuous workload** for users optimizing disk space with selective sync.
- **Perceived lack of parity** with competitors (e.g., OneDrive, Dropbox, Google Drive) offering Virtual Files functionality.

Considering the state-of-the-art of competitors (see below), it is a challenge to bring colleagues, family, and friends on-board.

# Background / State-of-the-art
To elaborate *"what 'files on demand' specifically refers to"* to reference the [Q&A Nov 2024](https://blog.filen.io/q-a/#files%20on%20demand):
- Files are synced as placeholder files that take up no space.
- They are downloaded for use on-demand.
- Downloaded files are cached, allowing a dynamic alternative to selective sync without going into settings.
- Individual files or folders can be marked as always available.

### This has been the norm for most large cloud storage providers
![Screenshot_onedrive](https://github.com/user-attachments/assets/d34da50d-4ca7-46e7-b9ef-cdd5599527b5)
<table><td><details><summary>Click to <b>view more screenshots</b></summary>

---
![Screenshot_dropbox](https://github.com/user-attachments/assets/dec1912c-a0f0-4769-bf66-ad5fa90bba07)
![Screenshot_Dropbox2](https://github.com/user-attachments/assets/84ed850b-6f12-4e7c-bf14-0b7c8fbcf3c0)

</details></td></table>

Competitor | Name of implementation
---------: | :--------------------
OneDrive    | "Files on-demand"
Dropbox     | "Smart sync"
OwnCloud    | "Virtual File System (VFS)"
GoogleDrive | "Google Drive File Stream"

# Proposed solution
Implement the [**Windows Cloud Files API / Cloud Sync Engine**](https://learn.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine) to enable a Virtual Files / Files On-Demand feature, allowing:
- Placeholder files (`CF_PLACEHOLDER`) to represent cloud files locally without taking up disk space.
- On-demand downloading of files when accessed, ensuring fast access with minimal storage impact.
- Option for users to mark specific files/folders as "Always available offline."

This will integrate seamlessly with Windows File Explorer, including sync icons and statuses, providing a familiar and modern user experience. Equivalent integrations exist for Mac OS. 

# Why this matters
1. **User Retention and Experience**: Users expect modern features that save storage and simplify workflows.
2. **Competitive Necessity**: Competitors like OneDrive and Dropbox have set a high standard with similar features.
3. **Efficiency**: Reduces unnecessary bandwidth and storage costs for users, particularly those with limited resources.
4. **Middle ground**: Strike a balance between fully committed download and online-only network drive.

Relying on the new network drive is not satisfying, because the drive vanishes as soon as the internet connection is lost. Furthermore, the network drive does not allow local files ignored from sync. Using traditional synced folders requires a lot of disk space and/or proper planning and continuous adjustment of selective sync.

**Comment by nagromc** [comment]
That is one quality feature request.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io

**Comment by nagromc** [comment]
This issue has been migrated: https://features.filen.io/posts/33
