### ISSUE TITLE
Sync locations are disappearing after every update on Windows and macOS.

### ISSUE THREAD

**Issue by uncharted-user** [FilenCloudDienste/filen-desktop#107]
**Describe the bug**
When the app is updated, the sync locations are getting removed. I have to create and add each one again. 

**To Reproduce**
1. Create Syncs
2. Update the app
3. Check the Syncs and they are gone

**Expected behavior**
Every setting shall be exactly it was after every update.

**OS (please complete the following information):**
 - OS: Windows 10, 11, macOS Sequoia
 - App version: 3.0.34

**People facing the problem:**
- https://www.reddit.com/r/filen_io/comments/1gw24bw/upgrade_of_filen_desktop_app_lost_existing_syncs/

**Comment by Dwynr** [comment]
This is expected when upgrading from legacy v2 to the new v3. The new version has been built from scratch, using a different localStorage format.

**Comment by uncharted-user** [comment]
> This is expected when upgrading from legacy v2 to the new v3. The new version has been built from scratch, using a different localStorage format.

Thanks for the reply. I think a warning could have been helpful for users who added numerous of sync locations over the year.  By the way, will that happen again when app will move to v4?
