### ISSUE TITLE
Sync client keeps flooding temp folder without giving a warning

### ISSUE THREAD

**Issue by flo-st** [FilenCloudDienste/filen-desktop#107]
OS: Win10
Sync Client v.2.0.5

If a folder is synced from the cloud, but the folder name contains a character that is not allowed in the Win10 naming convention, this folder cannot be created and the files contained in the folder are downloaded over and over again, although they have already been saved in the temp folder.
ETA remains permanently at 1min, the counter for synchronized files keeps increasing and no error message appears.

Although neither the file manager nor Win10 can create folders with such names, the client on Linux syncs them to the cloud and then passes them to Win10, resulting in this error.
**If the folder in the cloud is empty during it's first synchronization to Win10, an error message is displayed as expected.**

**Comment by Dwynr** [comment]
Known issue, will be fixed in the next update.
