### ISSUE TITLE
 [Feature Request] Allow user to chose wich files keep synced

### ISSUE THREAD

**Issue by zi0Black** [FilenCloudDienste/filen-desktop#11]
Hello,
I would like to propose a new feature.

Google Drive allows you to decide which files and folders to synchronize via a contextual menu in the file manager (see image attached at the bottom, sorry for the non-English language), I think this is a very useful feature.

Thank you.

![image](https://user-images.githubusercontent.com/13380579/136446454-9b574960-f7e2-4911-b0fb-166b9c631101.png)

**Comment by dermitdemdino** [comment]
Why can't you sync multiple folders in the apps. This is the only reason why I still hesitate to use Filen intensively.
