### ISSUE TITLE
Add a straightforward way of sharing a download link from the desktop app.

### ISSUE THREAD

**Issue by tuqueque** [FilenCloudDienste/filen-desktop#110]
Hey. I know you're still improving a lot of things in the app. But is a royal pain in the butt having to open my browser and go into my Filen account, search for a file I just uploaded and set-up the sharing options to copy the download URL.

I miss the MEGAsync feature of copying the download URL with just one click directly in the desktop app.
![Peek 2022-11-12 19-04](https://user-images.githubusercontent.com/13471025/201498516-f99d0b3b-a8c5-49d8-90f0-6bb42820d3fd.png)

It doesn't have to be THIS straightforward. But at least something like right-clicking the file I just uploaded and setup the sharing options, all from the desktop app without having to open the browser.

Thank you in advance!

**Comment by Dwynr** [comment]
Implemented, will ship with the next update.

Rel: https://github.com/FilenCloudDienste/filen-desktop/commit/8ba82499a9d7c8a46c21bc045199245b976239da
