### ISSUE TITLE
Two way sync in android mobile

### ISSUE THREAD

**Issue by Gaanee0** [FilenCloudDienste/filen-desktop#110]
**Is your feature request related to a problem? Please describe.**
It's for obsidian users who use apple sync or other syncs methods for their vault. There are literally 100k plus people who are using apple sync and they are frustrated with that service.

**Describe the solution you'd like**
Having a two sync in android and ios will be the perfect solution

**Describe alternatives you've considered**
I tried git alternatives. Remotly sync service. And frankly any other sync methods are not particularly privacy focused. Service like filen who focuses on privacy having a two sync in android will be a game changer

**Comment by Dwynr** [comment]
Wrong repo, but we are considering something like this for the new mobile app update.
