### ISSUE TITLE
Folder Info

### ISSUE THREAD

**Issue by ha7sh** [FilenCloudDienste/filen-desktop#111]
This is a basic feature which the most cloud providers have 

The folder info which shows total files contains, and total sub folders contains, and overall size 

Example - 

Files - 2353   Folders - 198   Size - 3.86GB  

This is not only for desktop 
This is for Desktop, web, Mobile

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/0f275e8efc5f21956286f817d19a5d5ad4f74095
