### ISSUE TITLE
Release app in Winget package manager

### ISSUE THREAD

**Issue by IkelAtomig** [FilenCloudDienste/filen-desktop#111]

**Comment by kachick** [comment]
They are keeping the definition since 2021, and is keeping to the latest. Is that not enough for us?


https://github.com/microsoft/winget-pkgs/pull/39054
https://github.com/microsoft/winget-pkgs/tree/f6979ffd868a8266682db8830ac1a8ddeca0088f/manifests/f/FilenCloud/FilenSync/2.0.24

**Comment by IkelAtomig** [comment]
They did have Winget for the older Clients but never updated the winget packages with the revamped ones. Didn't mention that one probably.
