### ISSUE TITLE
Syncing gets stuck with items "Queued"

### ISSUE THREAD

**Issue by ialexpw** [FilenCloudDienste/filen-desktop#112]
Hi there,

I'm moving over some files from another provider to Filen and I'm hitting this issue quite a lot, as the files are being discovered and then uploaded it gets to the point where some files will show as "Queued" and the progress bar constantly moves, but nothing happens. I cannot force a sync and Filen doesn't refresh to look for other changes/files.

I have to close the application and re-open it where it will scan and continue. Running the latest on WIndows 10 64bit.

Looks like below;

![image](https://user-images.githubusercontent.com/7994724/204028897-ee99fb23-76ec-4df6-9776-fa3964bb3b19.png)

This was experienced on multiple W10 machines with both way and single way sync.

I've checked the logs and nothing seems out of order in there, no issues shown at least. If you need more information I can try and get it! 😄

**Comment by Dwynr** [comment]
Next update includes huge performance improvements and general bug fixes, your issue should be fixed by then aswell. If not, feel free to open an issue again.
