### ISSUE TITLE
Option to require 2FA/email verification to delete all files and folders

### ISSUE THREAD

**Issue by rothos** [FilenCloudDienste/filen-desktop#112]
**Describe the problem**
Currently, a user can "delete all files and folders" using the desktop or web app without any additional security.

**Describe the solution you'd like**
I would feel more comfortable if there were an option to require an email verification, or other type of verification before deleting all files and folders. It's a standard type of security for significant account-level actions.

Edit: For this feature to be fully secure, disabling the feature once enabled should also require the same 2FA/email verification.

Edit 2: Or perhaps just requiring Filen password again to confirm deletion is an acceptable solution. In fact maybe I like it better.

**Comment by uncharted-user** [comment]
This should be added to feature request.

**Comment by rothos** [comment]
On second thought, maybe I prefer requiring Filen password to confirm deletion of all files and folders. (Or both)

**Comment by uncharted-user** [comment]
> On second thought, maybe I prefer requiring Filen password to confirm deletion of all files and folders. (Or both)

A double check is necessary when abnormal things are about to happen. Deleting all is unlikely.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io

**Comment by rothos** [comment]
This issue has been migrated:
https://features.filen.io/posts/12
