### ISSUE TITLE
MacOS Filen Desktop .filenignore display bug

### ISSUE THREAD

**Issue by rothos** [FilenCloudDienste/filen-desktop#114]
**Describe the bug**
When editing .filenignore on the Desktop app on my Mac, the name ".filenignore" appears behind the close/minimize/maximize buttons.

**To Reproduce**
Sync > Settings > .filenignore

**Expected behavior**
The text should be spaced so that it doesn't overlap with the buttons.

**Screenshots**
<img width="268" alt="Screenshot 2024-11-23 at 4 16 09 PM" src="https://github.com/user-attachments/assets/39615751-29a6-4535-b007-f2c2dbd7cd68">

**OS (please complete the following information):**
 - OS: MacOS Sonoma

**Comment by uncharted-user** [comment]
I found that adding a directory as `dir/` creates an empty directory, although I added this as ignored!

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/baa321fec87ba7c40985c70539e5016eb05ce309
