### ISSUE TITLE
Filen closes after automatic screen lock 

### ISSUE THREAD

**Issue by RasheedAZ** [FilenCloudDienste/filen-desktop#115]
I can't get Filen to run continuously.

After the screen turns blank due to inactivity, and I enter the password to unlock the desktop, Filen is no longer running or showing in the processes.

I cannot keep the screen unlocked for the long amount of time it will need to sync...

Would appreciate any help in figuring out what's causing the app to close. It happens several minutes after automatic screen lock, not straight after...

Using the latest Filen AppImage 2.08 on Pop!_OS 22.04 with Gnome 42.3.1

**Comment by Dwynr** [comment]
Can't reproduce: Need more information or a detailed reproduction report.

**Comment by RasheedAZ** [comment]
Sorry, I should have updated this: thankfully, it's not happening any longer after updating to version 2.0.12 :)
