### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#117]
Filen sometimes suddenly uses a high CPU %, leading to the computer heating up and the fans spinning audibly. The only fix is to close the app and reopen. There is no upload, download, or checking in progress.

macOS 13.0.1 (Intel), Filen 2.0.8

**Comment by Manuel-Steinberg** [comment]
Same with Windows 11 Pro (OS build 22623.1020), Filen 2.0.8
But reopen does not fix the issue on my side.

**Comment by Dwynr** [comment]
Next update for the desktop client will include huge performance and memory improvements, aswell as better power management. It's currently in internal testing phase and will release as soon as possible.

**Comment by Manuel-Steinberg** [comment]
@Dwynr I just updated to the newest version 2.0.10 and I can confirm that the heavy spikes to 100% are gone! 🥳
Nevertheless, for a desktop client that performs some background checks only, it is still too prominent with ~15% IMHO.

![image](https://user-images.githubusercontent.com/11491106/205964536-9b588945-f65a-4a05-9f55-222c977453b7.png)

When I quit filen the CPU is way more relaxed at ~3-5% (I also have a nextcloud client and OneDrive installed and running) ...

![image](https://user-images.githubusercontent.com/11491106/205965402-43d6771d-2ae1-4759-9ed4-f67c51ca4804.png)

**Comment by Dwynr** [comment]
Further improvements will follow, for now the focus was resolving memory leaks and unnecessary checks and function calls which were resulting in high CPU usage 👍🏼
