### ISSUE TITLE
Storage status is not dynamically updating.

### ISSUE THREAD

**Issue by uncharted-user** [FilenCloudDienste/filen-desktop#117]
**Describe the bug**
Storage status beside user icon on app is not updating real time. It only updates the storage if option/tab switched from Syncs to Contacts or any other option/tab.

**To Reproduce**
1. Open the app
2. Start the sync
3. Observe the storage status

**Expected behavior**
The status should reflect real time storage.

**Screenshots**
![image](https://github.com/user-attachments/assets/38d8af60-67f9-4471-93ef-881ca07c757d)

**OS (please complete the following information):**
 - OS: Windows, macOS, Linux
 - App version: 3.0.34

**Comment by rothos** [comment]
Can reproduce. Even cmd+r to refresh does not update it immediately for me.

**Comment by Dwynr** [comment]
It's cached on the backend and updates approx. every 30-90 seconds.

**Comment by uncharted-user** [comment]
> It's cached on the backend and updates approx. every 30-90 seconds.

Could you please make this update related to activity e.g. when files are syncing the update cloud be few seconds? However, it is not updating at all, not unless I switch the tab!
