### ISSUE TITLE
[Feature Request] A setting in desktop app whether versions should be created in the drive during sync or not

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-desktop#119]
When files that already exist in Filen Drive have changed on my Windows device and then are synced to Filen Drive with the Desktop App, versions of these files are created in the drive. I like that a lot.

I have files in sync that are changed often on my Windows device and so many versions are created. It would be helpful to specify in the sync settings per sync whether versions are to be created or the file will be overwritten in the drive without creating a version.

**Comment by Dwynr** [comment]
An option to enable/disable file versioning will be added to the Web Drive settings in the near future.
