### ISSUE TITLE
Filen "holding a lock" on files inside the sync folder

### ISSUE THREAD

**Issue by xmrv** [FilenCloudDienste/filen-desktop#12]
PC user here.

I recently moved a java project to the cloud to be able to sync and work on my files at the same time.

While working with IntelliJ Idea I realized that something was deleting one of my classes that I work on when I try to open it or run it. 

After an hour or so I discovered Filen desktop app was in a constant state of syncing and "holding a lock" on the file hence the failure to work with the file. When I closed Filen, everything worked out perfectly.

**Comment by Dwynr** [comment]
It's a known issue, I wouldnt recommend live editing a bunch of files at the same time right now (like an IDE does), will look for a fix.
