### ISSUE TITLE
Not recognizing lack of internet

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#120]
Filen isn't recognizing that it's offline when there's no internet. At least, nothing is displayed (continues saying "Everything synced"). This issue was introduced in today's update.

macOS 13.0.1 (Intel), Filen 2.0.10

**Comment by Dwynr** [comment]
Regression, fixed with https://github.com/FilenCloudDienste/filen-desktop/commit/57bb99569bc8c508402112ff1920b41670716c10
