### ISSUE TITLE
Clicking Filen tray icon auto-opens the app and changes focus to the app

### ISSUE THREAD

**Issue by rothos** [FilenCloudDienste/filen-desktop#121]
**Describe the bug**
The Filen tray icon has an "Open" option. However I don't get a chance to click it, because merely clicking the tray icon opens the app itself. If the app is open, the focus is changed to the app.

**To Reproduce**
1. Click close on the Filen desktop app. Click the Filen app tray icon and wait a second.

**Expected behavior**
Clicking the tray icon shouldn't open the app, it should only open the tray icon menu.

**Screenshots**
Screen recording:
https://github.com/user-attachments/assets/8d1d60d0-1431-4b25-a145-75f9a5b59469

**OS & Filen app version (please complete the following information):**
 - OS: MacOS Sonoma
 - Filen Desktop Version 3.0.34 (3.0.34)

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-desktop/commit/709f7eb7a5022dc7a4d9a9174ba26a3d9d239383
