### ISSUE TITLE
Files are moved to the trash when the sync source is unavailable (new users are afraid Filen lost their files)

### ISSUE THREAD

**Issue by Mangoes** [FilenCloudDienste/filen-desktop#122]
**Describe the bug**
This bug also happened to users who have their source drive 100% connected and available.

But I think it's the same old problem as when a sync source is unavailable (due to a drive failing to mount caused by a filesystem error or a disconnected removable drive, etc...), Filen moves the files into the trash.

The user then has to manually intervene to move the files back. (If he doesn't, Filen will restart the complete sync again when the source is available).

Regularly, there are users who don't know what happened and are afraid that Filen lost their files.

Other cloud services don't have this problem.

(The "local backup" sync option doesn't solve this problem, as the other advantages of the normal sync options aren't available in this case).

**To Reproduce**
1. Make a source drive unavailable 
2. The files disappear in the cloud
3. User is in shock: "oh my God, my files are lost!".
4. Pfffewww ... thank God they are in the trash.

**Expected behavior**
1. make it so that the system automatically moves the files back from the trash to their folders as soon as it sees the source files available again. So the user doesn't have to intervene manually.

2. also add an option in the sync settings to manually flag a drive as removable storage (so when you disconnect your USB drive, Filen doesn't move the files to the trash).

3. also having the app informing the user when it moves the files to the trash would prevent the shock of thinking the files are lost, in such cases.

**Comment by Dwynr** [comment]
This is most likely a good idea. I will look into it.

**Comment by szapp** [comment]
> 1. make it so that the system automatically moves the files back from the trash to their folders as soon as it sees the source files available again. So the user doesn't have to intervene manually.

This sounds more like treating a symptom rather than the problem. A safeguard checking if the sync-location, i.e. the local root-folder of a sync exists, might be better. Like your 2nd suggestion, just in general. No need to complicate things by implementing to flag as removable medium.

**Comment by Mangoes** [comment]
> This sounds more like treating a symptom rather than the problem. A safeguard checking if the sync-location, i.e. the local root-folder of a sync exists, might be better. Like your 2nd suggestion, just in general. No need to complicate things by implementing to flag as removable medium.

And at least asking for user confirmation before moving the files to the trash, if the source drive is not available.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-sync/commit/dea27833b2e7d2e7c798c7ec24a637b14ca153e9
