### ISSUE TITLE
Remove from macOS Dock? 

### ISSUE THREAD

**Issue by brokosz** [FilenCloudDienste/filen-desktop#123]
Can we get an option to remove the icon from the Dock, or choose Dock versus Menu Bar? No need to show the app running in both, especially if the app is set to run at system startup.

**Comment by scollovati** [comment]
@flo-st @Dwynr  suggested to use `--hidden` https://github.com/FilenCloudDienste/filen-desktop/issues/83#issuecomment-2483023110, but on Macos does not work `open -n /Applications/Filen.app --args --hidden`

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-desktop/commit/a6ddcf68596b20695a766d1c907fe5cbcd6cbba5
https://github.com/FilenCloudDienste/filen-web/commit/3b5b26aa3a1e47f38b8bcf482f59570b741a6d14
