### ISSUE TITLE
how to get the old desktop client?

### ISSUE THREAD

**Issue by yashgorana** [FilenCloudDienste/filen-desktop#124]
Firstly, I want to say that I've been a happy customer for 2+ years and appreciate the team's vision and commitment to ship new feature. However, the new app is a step back in usability and stability and feels more of a beta app than a full release - the current set of issues on Github & Reddit are a reflection of the state of the new desktop client.

Is there a way we can get the previous stable v2 version? I can't seem to find it on GitHub releases?

**Comment by rothos** [comment]
I have the installers for a previous version, you can email me (there's a link to my website in my bio, find it there). I'm not sure how long they'll be supported, of course.

**Comment by devastgh** [comment]
https://github.com/FilenCloudDienste/filen-desktop-legacy/releases
