### ISSUE TITLE
Not syncing after wake from sleep

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#124]
On some wakes from sleep mode, Filen syncing freezes and refuses to update. It only says "Everything synced" permanently. Only workaround is to quit and reopen, only for it to come back a few hours later.

macOS 13.0.1 (Intel), Filen 2.0.10

Update: Made a mistake, I thought it was caused by sleep mode. It just happened while awake the whole duration. It just stops syncing. Force syncing also does nothing. This is a serious new issue.

**Comment by Dwynr** [comment]
Need more information on how to reproduce it.

**Comment by privacytime101** [comment]
@Dwynr It happened again earlier today for the first time since the fix. My device was on sleep all night and I noticed it just wasn't syncing in the morning a few hours later. 

Nothing really out of the ordinary in the logs, except for `ERR_CONNECTION_REFUSED` for update checks all night. Why is the auto-update even running while the device is asleep? A bit confused.
