### ISSUE TITLE
Enhancing Storage Management with Customizable Trash Emptying

### ISSUE THREAD

**Issue by onewhowalkedalone** [FilenCloudDienste/filen-desktop#125]
I would like to request the ability to customize my device's trash emptying schedule.
Specifically, I'd like to have the option to:
 - Disable Automatic Emptying: Completely turn off automatic trash emptying.
 - Set a Custom Emptying Schedule: Allow me to specify a preferred interval between emptying, ranging from X days to X years.
 
By implementing these options, users can proactively manage their storage space, reduce the risk of accidental data loss, and tailor the device's behavior to their specific workflows.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
