### ISSUE TITLE
"Quit Filen" not working as expected

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#125]
The "Quit Filen" or "Quit" from the menu bar dropdown does not close on the first try. The process usually needs to be repeated 2-3 times before it closes, as it thinks that the click on the confirmation (macOS "Are you sure you want to quit?" prompt) is the user trying to click away from the Filen menu (Filen dropdown with event log, etc.). 

macOS 13.0.1 (Intel), Filen 2.0.10

**Comment by Dwynr** [comment]
Also a regression, fixed in the next update.
