### ISSUE TITLE
Bugs after Update to v2.0.11

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-desktop#127]
I have received an automatic update from version 2.0.10 to 2.0.11 on Windows 10.

**Wrong Icon Text in Taskbar Notification Icon** Not a problem, but...
![grafik](https://user-images.githubusercontent.com/116081825/206707573-da809ae1-58ae-45cf-9c4a-85cd7aa82461.png)

**...now I have two entries for Filen in the Windows Settings for displaying the App Icons in the notification area:**
![grafik](https://user-images.githubusercontent.com/116081825/206708259-fd156755-8e55-48d4-babe-5c192c5efdca.png)
![grafik](https://user-images.githubusercontent.com/116081825/206708331-d76668f5-62e4-47e9-bc24-55eb303f108d.png)

**The "Paused"-switch for pausing or activating synchronizations no longer works.** Clicks do not change the state, not even the button in the sync overview.
![grafik](https://user-images.githubusercontent.com/116081825/206708487-37d0f21a-9b04-4933-973f-a19f47b8cee9.png)

**Comment by Dwynr** [comment]
Thanks for reporting, will try to reproduce and release a hotfix.
