### ISSUE TITLE
Auto Update Not Working

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#128]
The update from 2.0.10 -> 2.0.11 has been failing on my device. 

The first time the prompt came up, there was a checkmark saying that it will now start the flow. I closed the prompt, waited for 10 minutes and nothing happened, so I quit the app and reopened. 

The install prompt came up again, this time saying it needs to install ("close" button was now "install). It loaded for a few seconds, then the prompt closed and nothing happened once again. I checked Filen and it was stuck on "Checking Changes..." permanently. Relaunching did the exact same thing. 

I'm currently unable to update unless I download the new release manually.

macOS 13.0.1 (Intel), Filen 2.0.10

Update: Restarting my computer fixed it. A macOS "Verifying Filen..." came up on launch and it now says 2.0.12 in the Filen app. It's still weird that it happened though.

**Comment by Dwynr** [comment]
Fixed in 2.0.12.
