### ISSUE TITLE
HEIC and Apple ProRAW first-class support

### ISSUE THREAD

**Issue by pjedruszuk** [FilenCloudDienste/filen-desktop#128]
**Is your feature request related to a problem? Please describe.**
Currently, HEIC and ProRAW files lack thumbnails, can't be opened in a preview through the Filen desktop app. 

**Describe the solution you'd like**
Both formats recognized as image formats, with all the features other image formats get.

**Describe alternatives you've considered**
None available. Either the support is there or not.

**Additional context**
This could lay foundations for the rewritten mobile (iOS specifically, but likely all the platforms can benefit) apps, which is apparently planned. Current version of the iOS app supports HEIC but doesn't support ProRAW which causes the ProRAW photos not be visible in the "Photos" tab. This might create an appearance, that the photos are not synced up properly, unless the user checks the underlying storage.
Having a proper support for both formats in a Filen platform universally would bring a much better user experience.

**Comment by Dwynr** [comment]
https://features.filen.io/posts/3/heic-and-apple-proraw-first-class-support
