### ISSUE TITLE
[Feature Request] Ignore .part files by default

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-desktop#129]
Some browsers save parts of a download in .part files before it's completed. Filen tries to save these broken chunks by default, making that sync totally useless. I can add `*.part` to my ignore list, but having it as a default option would be better in my opinion.

**Comment by Dwynr** [comment]
That's what the .filenignore settings is for. ".part" files do not default to temporary downloads, therefore excluding them by default is not an option.
