### ISSUE TITLE
Close To Tray Setting

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#130]
**Is your feature request related to a problem? Please describe.**
Unable to close app and have it running in the tray

**Describe the solution you'd like**
To have a setting which can allow to close the app to the tray

**Describe alternatives you've considered**
None

**Additional context**
Minimized to tray setting has been added. Please add a close to tray feature. The older version of the Filen sync app was able to be closed to tray. I do not want to have the Filen window minimized to my panel when it is running in the background.

**Comment by Dwynr** [comment]
Duplicate https://github.com/FilenCloudDienste/filen-desktop/issues/102
