### ISSUE TITLE
File sync/upload gets stuck sometimes

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-desktop#131]
Sometimes, rather rarely, the sync / file upload of the Windows app stops and I see the following picture:
![grafik](https://user-images.githubusercontent.com/116081825/208911536-31564235-2861-47a7-9cab-0451e2d23fbc.png)

It happens with different files (and it seems more often with larger files, but I am not sure about this). It helps to restart the app and then the sync starts again.

**Comment by Dwynr** [comment]
If you could try to reproduce it a few times and post the results here I can take a look.
Does it happen when the client has been running for a few hours or is it random?
Need more information.

**Comment by Dwynr** [comment]
1.) -> We have not noticed any 504 errors/timeouts on our side
2.) -> Has been fixed in the latest 2 versions

If you notice issues regarding the two above points in the latest version feel free to open an issue again, otherwise I am closing it as done.
