### ISSUE TITLE
[Feature Request] Export Local Event Log (as CSV)

### ISSUE THREAD

**Issue by xthrk** [FilenCloudDienste/filen-desktop#132]
In the Settings unter General there is a button to clear the local event log. It would be nice to have a function to export the local event log (sync log) in a readable format like CSV:
- Timestamp (Date, Time)
- Folder local
- Folder cloud
- Filename (maybe empty, for example if a folder is created)
- Action (uploaded, downloaded, renamed local, renamed cloud, deleted local, deleted cloud, ...)
- Errormessage (if possible in case of an error?)

**Comment by Dwynr** [comment]
The event log is truncated to 1024 items at a time, as it is just visual. Exporting would never include the complete full log from the point of installation.
