### ISSUE TITLE
[2.0.12, Windows] Files getting deleted

### ISSUE THREAD

**Issue by RichardPaulAstley** [FilenCloudDienste/filen-desktop#133]
Echoing to this : https://www.reddit.com/r/filen_io/comments/zrc2to/missing_files/

Some people are reporting files just disappearing from everywhere without any reason. Some user even did a try that way : 

> 1. installed Filen (Win)
> 2. created a directory named Filen Sync
> 3. connected it to a directory with the same name on Filen (Web)
> 4. copied some thousands file in this directory (Photos, Documentes, all kinds of stuff)
> 5. Let is SYNC! :-)
> 6. O.K. Everythings fine because I compared everything in Filen Sync with the files on my PC
> 7. Now comes the interesting part!
> 8. I've created another directory UNDER Filen Sync named Filen Sync\Backup
> 9. MOVED all the files in Filen Sync to Filen Sync\Backup (that was fast!)
> 10. Compared everything in Filen Sync\Backup with the files on my PC
> 11. Surprise! ONE file was missing. A WORD-document from 2018.

Without any way to figure out in which situation it happens, we can only assume it's random. And it can be a real issue for a software where the purpose is to keep everything.

Would the best solution to be to downgrade meanwhile this is fixed ?
Thank you.

**Comment by Dwynr** [comment]
Without a proper bug report with steps on how to reproduce the issue exactly (including the directory tree used) there is not a lot we can do.

"Surprise! ONE file was missing. A WORD-document from 2018." is pretty vague.

**Comment by RichardPaulAstley** [comment]
I could only agree on the vague setup of the user in the reddit post.

But I think it's quite an issue if this popped up randomly for multiple users with the last version. Maybe try to check with these users (me included) to do a fast setup and see if we/they could log anything, because it's quite a critical problem here.

**Comment by Dwynr** [comment]
If you (or others in that case) can reproduce it with a proper report (like mentioned above) we can look into it.

**Comment by RichardPaulAstley** [comment]
I didn't saw any file removal in my case since it's a mess, but I'm worried about that critical issue. 
Just used the fact to be a regular GitHub user to share some issues shown in the reddit. Maybe it's important to reach to them to do some testing on that part and figure out what's going on.

Thanks !

**Comment by RichardPaulAstley** [comment]
Seems to be gone from everywhere, randomly. 
So it'd make Filen unusable atm.

**Comment by rolandsz** [comment]
It happened to me as well, some files (around 100 GB in total) are simply gone without a trace and support claims they are deleted permanently. I used both the Linux and Windows sync clients, and I suspect it was the Windows one that messed it up. The files are not in the trash and they are not mentioned in the event logs - I scraped all events from my account, the only record is related to the upload of the files, nothing about deletion/move. I strongly recommend not using any of the cloud -> local sync modes, especially not the two-way one. I lost my trust in the service, E2E was a great selling point for me, but reliability is far more important. It's also concerning that there is no backup from which files can be restored in case of an event like this.

**Comment by addicted2qubes** [comment]
I have noticed uploading large directories with many files and everything synced. Then later there are fewer files in the directory that was uploaded than were in the original backup. I take my local backups and move them to Filen so I know how many files are in the local backup. I thought it was based on duplicate files being deleted or files that were 0 in size, but I am not sure. I will have to upload certain directories again because of this and since I don't know which file is missing or what files are correct I will just delete what I hate and upload again.
