### ISSUE TITLE
Huge RAM Usage

### ISSUE THREAD

**Issue by RichardPaulAstley** [FilenCloudDienste/filen-desktop#134]
Another issue i've noticed while using Filen.

![image](https://user-images.githubusercontent.com/25870563/208935096-1aa8418f-9433-428c-8aa0-531fb2f72166.png)

**The issue here is that Filen has ALL the sync links in pause (following the 2.0.12 errors) so pretty much shouldn't do anything.**

I've tried a lot of Cloud Clients, and Filen is the one that uses the most RAM possible. We could say that ~400MB isn't a lot, I do think it is. A lot. If you have for example a 8GB RAM, it'll get annoying if you use a browser + a game for example.

I've got cases (with older versions) where it could go up to 1,5GB while writting stuff. But I'll ignore ethat part.

I've compared a few and here's the two extreme cases :

- OneDrive with 30MB. 
- NextCloud with around 70MB
- Filen with 400MB+

It seems really a lot compared to the others. I've read that there was some improvements in the past about performances, but in that part, I didn't see anything improving.

Thanks a lot !

**Comment by Dwynr** [comment]
Even when the client is idle and does nothing it still has both the remote and the local directory tree in memory cache. It caches all metadata of encrypted files. That way it does not need to decrypt files again in case of a remote/local change, making the sync operations pretty fast. If you have a large directory tree this can result in a few hundred MB of usage. 

Every other client you have mentioned is not fully end to end encrypted and therefore does not need to keep every piece of metadata in it's cache. They can compare the plain directory trees provided to them.

We've drastically improved the RAM usage compared to previous releases and will keep improving it in the future.

I've attached a screenshot of the client running with a small directory tree actively synced, just to show how the metadata cache eats up a bit of RAM. When syncing a small directory tree memory usage is normal.

![Screenshot 2022-12-21 184751](https://user-images.githubusercontent.com/14013321/208971053-b616efaa-9ca5-489a-98f1-62f058a05d07.png)

**Comment by RichardPaulAstley** [comment]
Thanks a lot for your complete answer. My issue was not really an issue as such, more a suggestion or something to talk about since it's the thing i've the most trouble with Filen (and the only one).

From that i've two question (one quite noobish sorry) : 

1. Would it mean that I should reduce the amount of sync folders ? Atm i've 9 main folders to sync. I could reduce to 3 easily. But it'd imply more subfolders. Would it be of any influence ? or just it'd be the same based of the amount of folders / files
2. Could it be possible in the future to have settings to reduce that RAM by for example (yes it'd go about some basics of Filen but we never know) allowing some folders to not be full encrypted or something more basic to save some RAM use ? Would be an option for lower systems 

Thanks o/
