### ISSUE TITLE
Read Only files are silently skipped from sync

### ISSUE THREAD

**Issue by maelstrm-code** [FilenCloudDienste/filen-desktop#135]
**Describe the bug**
Sync shows as "Everything synced" when files are missing. There are no issues, and there is a smiley face in the issues tab.

**To Reproduce**
Set up a sync, have some files in the target source folder that are read only, let the sync run, check that the files do not sync.

**Expected behavior**
The files should sync. It is legitimate to want to sync (upload) read only files.
Failing that, there should be an error and alert advising the user that files did not sync, the reason, and how to fix it.

**OS (please complete the following information):**
 - OS: Windows 11
 - Hardware configuration Not relevant
- Filesystem and Disk type used: SSD, NTFS, Bitlocker enabled.

**Additional context**
This has been referenced by others on reddit over the course of at least 2 years.

**Comment by Dwynr** [comment]
This will be fixed in the next update for the "localToCloud" and "localBackup" sync modes.
