### ISSUE TITLE
Right click systray icon and Exit = Open the app !

### ISSUE THREAD

**Issue by Dominic-t3ch** [FilenCloudDienste/filen-desktop#136]
**Describe the bug**
In version 3.0.39. When right click on the systray icon, it open the app Window instead exit (shutdown) the app.

**To Reproduce**
1. Right click on systray icon
2. Click on Exit
3. The app that was minimzed is opened instead to exit

**Expected behavior**
The app should exit (shutdown) instead to open

**OS (please complete the following information):**
 - OS: Windows 11 23H2
 - Hardware configuration : Dell laptop Intel i7-11800H, 32 Go RAM
- Filesystem and Disk type used : SSD with NTFS

**Comment by Dwynr** [comment]
Thanks for reporting.

https://github.com/FilenCloudDienste/filen-desktop/commit/55da2c448b667ffae0d114fb0d48de2294a769ca
