### ISSUE TITLE
Case-insensitive issue on the website

### ISSUE THREAD

**Issue by erikrodrgz** [FilenCloudDienste/filen-desktop#14]
I could not rename some folder "foo" to "Foo" on the website, it accuses that the folder already exists.

I think that the case-insensitive could be a problem if I upload two folders/files  in the same directory with the same letters, like the example above. 

I did not find a place to report an issue for the website.

**Comment by Dwynr** [comment]
I have noted it down and will look for a fix. Closing this issue as it is not really related to the sync client.
