### ISSUE TITLE
[2.0.13,Linux] Appimage x64-86 won't open

### ISSUE THREAD

**Issue by ahmuro** [FilenCloudDienste/filen-desktop#141]
Fedora 37, running the appimage does nothing, not even error message. This either by itself or through AppimageLauncher. File has the proper permissions.

**Comment by Dwynr** [comment]
Download the AppImage, then

`chmod +x ./filen-AppImage.xxx`
`./filen-AppImage.xxx`

in a Terminal. It should at least print something to the terminal.

**Comment by ahmuro** [comment]
there were a few errors
first one was with Appimagelauncher, already solved
then one about an invalid certificate, I think that was just my dns blocking sentry.io
solved those, logs says this

```
22:18:16.211 › Checking for update
22:18:16.225 › Checking if an update is available
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
22:18:16.277 › Initializing startup windows
22:18:16.355 › Error: ENOENT: no such file or directory, scandir '/home/ahmurx/.config/filen-desktop/db_v1'
22:18:17.092 › Update for version 2.0.13 is not available (latest version: 2.0.13, downgrade is disallowed).
22:18:37.094 › Startup windows error
22:18:37.096 › Error: Error: ENOENT: no such file or directory, open '/home/ahmurx/.config/filen-desktop/db_v1/5e51fbb1d80922a4cb1ea2569984300274d40dbc8b2bb76bd7063e18989e514b.json.1863623199'
    at Timeout.write [as _onTimeout] (/tmp/.mount_filen_yaf4xx/resources/app/src/main/lib/db/db.js:112:35)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
```
but checking the processes and is actually there

![image](https://user-images.githubusercontent.com/62005324/209903205-b1353bc5-0c3d-4f22-a012-2eda7e686e7a.png)

so it seems to be running it's just that I have no gui

**Comment by ahmuro** [comment]
not sure yet since i have no other linux device to test, but i see that is working for other people si it is probably an issue on my side
will close and see what happens
thanks

**Comment by Dwynr** [comment]
Thanks for the logs, issue should be fixed now.
Download the latest version and let me know:

Linux x86_64: https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
Linux arm64: https://cdn.filen.io/desktop/release/filen_arm64.AppImage
