### ISSUE TITLE
No tray icon on Linux

### ISSUE THREAD

**Issue by carobinario** [FilenCloudDienste/filen-desktop#143]
The tray icon has been removed because some linux distrubutions do not have libappindicator installed by default - which makes electron crash. Users would have to install the library manually and that's not a solution either. For now it will stay disabled - though temporarily until we found a better solution.

> _Originally posted by @Dwynr in https://github.com/FilenCloudDienste/filen-desktop/issues/123#issuecomment-1343159057_

Hi,
I updated to 2.0.14 and tray icon is still missing. Any news? Thanks

My system:

Operating System: openSUSE Tumbleweed 20221226
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.0-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600 CPU @ 3.30GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-desktop/commit/7c95547ed1db47f69caedceb96c601522d9f7cd1
