### ISSUE TITLE
Folder tree names on the left get cut off and you can't move the divider to reveal them

### ISSUE THREAD

**Issue by eladbari** [FilenCloudDienste/filen-desktop#144]
**Describe the bug**

**To Reproduce**
Just using the app- you can't move the divider left and right. It's locked.

**Expected behavior**
It should let me move the divider like in any folder/finder or app that lets you do so

**Screenshots**
![image](https://github.com/user-attachments/assets/c1b1c129-3741-4f78-b97e-48d6599d3a5e)

**OS (please complete the following information):**
 Windows 10

**Comment by Dominic-t3ch** [comment]
More a feature request than a bug. But I agree with this one. The left panel isn't wide enough!

**Comment by Dwynr** [comment]
Not really a bug, more like a feature request. For feature requests please use https://features.filen.io/.
