### ISSUE TITLE
Since 2.0.12 on Windows, Filen no longer uploads/updates read-only files (and deletes them on the other side of the sync if they were already present)

### ISSUE THREAD

**Issue by adorbabble** [FilenCloudDienste/filen-desktop#144]
Hi. I currently have one sync from Local to Cloud. After I updated Filen Desktop to 2.0.12 a while ago (I’m on 2.0.14 now), I noticed that some files were moved to the trash bin on the cloud. After having a look at Filen’s logs and contacting support, I found out that Filen has a permission error ("Error: EPERM: operation not permitted") on files that have the “Read-only” checkbox checked : right-click on a file > Properties in the contextual menu, then in the “General” tab, section “Attributes” at the bottom

When I saw the changelog of version 2.0.13, which contains "Fixed ENOENT/EPERM issues on windows", I thought that this bug had probably been fixed, but I’m seeing now on 2.0.14 that this is not the case.

I thought it was worth reporting this problem here on GitHub so that it gets more attention, too, because at the end of my support ticket, the support person replied “Our developers are working on bringing more functionality to our clients. I will forward your suggestions.”, but this looks like a bug to me.

I’m not sure whether operating systems other than Windows are affected (I also use Linux on my laptop, but haven’t installed Filen there yet)

**Comment by gjmv** [comment]
Hi, i have the same problem.
I don't undestand what was happening until read this issue.
I have problems uploading git folders. Objects in .git\objects don't upload.
Now I observed that all objects are read only. 
Do you plan an fix to this? or is the expected working?
Regards

**Comment by Dwynr** [comment]
This will be fixed in the next update.
