### ISSUE TITLE
[2.0.14] Files not updating well, lost files.

### ISSUE THREAD

**Issue by RichardPaulAstley** [FilenCloudDienste/filen-desktop#145]
Hi,

I'm using Filen with 4 PCs, and the idea was also to sync some local storage files for some programs. 
Filen has huge issues to instant update / sync files (which should be the job), and that made me lost important files and folders because of being overwritten without any file. 

I can't really provide any log, since it's really a synchronization issue, where the tool ended up with corrupted files / gone files. So it created new files, erased everything and then Filen had the time to update well. I was able to restore with versionning but still with

It starts being difficult to use Filen correctly if the synchronizing tool / part doesn't work well like this case.

Thank you

**Comment by azzadrood** [comment]
Hello,

I have almost the same problem with some files not being uploaded to the cloud.

<img width="627" alt="Screenshot 2023-02-17 at 14 16 42" src="https://user-images.githubusercontent.com/9199523/219651733-231ee8e5-e755-4d51-b4c5-60df659c26f3.png">

This is the filen sync folder settings

<img width="1437" alt="Screenshot 2023-02-17 at 14 17 17" src="https://user-images.githubusercontent.com/9199523/219651790-bcf561b6-ca96-4c66-a366-94b87dc40d4e.png">

This is the local folder that should be synced with the cloud.

![Screenshot 2023-02-17 at 14 17 34](https://user-images.githubusercontent.com/9199523/219651852-b768e9bd-e50a-4186-895f-7bc212ee634d.png)

This is the cloud folder

<img width="370" alt="Screenshot 2023-02-17 at 14 19 07" src="https://user-images.githubusercontent.com/9199523/219651983-44b302ce-e7f6-4348-8fcf-5b5304215fc2.png">

This is filen saying that all is synced

I'm using filen v2.0.16 on osx 13.2.1 (22D68).

If you need more information or logs I can provide them as this is an issue I have had for more than 1 month.

Also, the current cloud files have been uploaded manually from the web app, as the desktop app didn't upload them correctly. Before uploading them manually the desktop app from 1st computer didn't upload them correctly. The local computer screenshot is from 2nd computer.

**Comment by joaobarcia** [comment]
I am having similar issues. Happy to send any relevant logs. Also similar issues on mobile with MobileMedia instant sync.
