### ISSUE TITLE
Folder tree address line above fails to show the actual folder you're in

### ISSUE THREAD

**Issue by eladbari** [FilenCloudDienste/filen-desktop#145]
**Describe the bug**
Folder tree address line above is anchored to show the ROOT folder the file is saved in, and when the names of the folder tree gets long - you will not be able to see where you are at. 
In the screenshot below I am inside a folder called "Final Pics". Only stretching the App's UI reveals where I'm at

**To Reproduce**
If you go down a folder tree and the full name of the directory gets long- then you won't see above in the address line - the folder you are in. You'd have to stretch the UI till it reveals itself. The end result is that you can only click earlier "parent folders" so you end up going way back to the root folder instead of 1-2 folders back.

**Expected behavior**
The revealed folder name should be anchored to the right of the address line so I can actually click back on the folder I want to go back to. As you go back up the folder tree- 'parent' folders should be revealed on the left side of the address line. So, just anchoring the seen to the right. Not the left. I don't need to see "Cloud Drive" or "M" or "PROJECTS [SSD]" because I'm deeper in that folder tree.  

**Screenshots**
![image](https://github.com/user-attachments/assets/f9b7a666-690c-4fcf-b298-315a43d3a4e6)

**OS (please complete the following information):**
Win10

**Comment by Dwynr** [comment]
Not a bug, that's just the line wrapping if the parent container is not large enough to display the complete file path. We could truncate it in the middle to show the start and end inclusive. For feature requests please use https://features.filen.io/.

**Comment by eladbari** [comment]
> Not a bug, that's just the line wrapping if the parent container is not large enough to display the complete file path. We could truncate it in the middle to show the start and end inclusive. For feature requests please use https://features.filen.io/.

Ok, I will post it also under feature requests, but I think there's zero functionality in showing "earlier" folders under the folder tree. If the folder tree was aligned to the right [i.e- the latest folder would appear on the right of the address line]- it would enable jumping back via clicking another folder and as you go back- "older" more "root" folders would appear. Just like Win10 works.
