### ISSUE TITLE
Search request doesn't find the files unless I go straight to the folder where it is at

### ISSUE THREAD

**Issue by eladbari** [FilenCloudDienste/filen-desktop#146]
**Describe the bug**
A search request doesn't work unless I go deeper into the actual folder it is saved in. Only then it finds the file/folder.

**To Reproduce**
Just search for anything that is stored 2 folders down from the parent folder you search it. It will not work. Now, get into the actual folder and it will find it. The search goes only 1 level down, and not endlessly, how it should.
 
**Expected behavior**
If I search for a file called "Ben" in my root folder - it should find it. I can't remember where I stored every file so searching under my whole cloud storage should reveal my requested file. ++ ALSO, Right click on it- should display "Properties" and lemme copy the folder addres in the cloud it is at.

**Screenshots**
![image](https://github.com/user-attachments/assets/76d2d825-db9a-4ef3-927f-e6f2698eff7a)

**OS (please complete the following information):**
Win10

**Comment by Dwynr** [comment]
Not really a bug, more like a feature request. For feature requests please use https://features.filen.io/.

**Comment by eladbari** [comment]
> Not really a bug, more like a feature request. For feature requests please use https://features.filen.io/.

Wow, this too is a feature? Ok...
