### ISSUE TITLE
Selecting specific files to get a shareable link to - is unavailable

### ISSUE THREAD

**Issue by eladbari** [FilenCloudDienste/filen-desktop#147]
**Describe the bug**
I have 30 files in a folder. I just want to Ctrl+highlight specific 5 files, right click them and share only them with someone to download - and I can't have that option on the right click. Right click > 

**To Reproduce**
Ctrl+Click a few selected filed in a folder + right click. You have much less options and no sharing option for a Public link.

**Expected behavior**
Filen App should let me freely choose what to include in a public link and what not. It should not be a global thing that I can only share 1 file or a full folder or nothing.

**Screenshots**
![image](https://github.com/user-attachments/assets/875c2423-1b0a-4eae-96ab-14ec0f9b5878)

**OS (please complete the following information):**
Win10

**Additional context**
Thanks for fixing all that!

**Comment by Dwynr** [comment]
Not really a bug, more like a feature request. For feature requests please use https://features.filen.io/.

**Comment by eladbari** [comment]
> Not really a bug, more like a feature request. For feature requests please use https://features.filen.io/.

Thanks for clarifying. I was sure this was a basic feature to use. I will post there
