### ISSUE TITLE
Stuck on v2.0.12 even after updating

### ISSUE THREAD

**Issue by Re4mstr** [FilenCloudDienste/filen-desktop#149]
So after the x.14 update all my w11 machines are facing this weird issue.

After updating - and after a restart- I am once more greeted with this update prompt, and the version that is running is still x.12.

I am willing to provide any logs if necessary, but since all my machines has this issue, it can't be hard to replicate.

![screenshot](https://user-images.githubusercontent.com/15211713/210432136-4eefd245-eeae-4483-8265-d16820f3156c.jpg)

**Comment by Dwynr** [comment]
Install the latest version from our website manually. Auto update will be fixed asap.
