### ISSUE TITLE
A bit of help with Rust↔Filen API interface?

### ISSUE THREAD

**Issue by EnoughTea** [FilenCloudDienste/filen-desktop#15]
Hi guys! 

Inspired by your great service and open-source client, I decided to make a [Rust↔Filen API interface](https://github.com/EnoughTea/rust-filen). Things were looking good, I got a lot of API queries working. It was fun implementing window.crypto/CryptoJS calls in native lib terms, and looking at filen-desktop source code to the point of memorizing it. However, recently I kinda hit a wall, with wall being implementing file upload, aka `doUpload()` from filen-desktop.

I am grateful for any help received, but if you are too busy to help, I would understand. So, to the point:

My encrypted file chunks can be uploaded to Filen successfully, at least Filen returns "Chunk stored" for every chunk. However, when I try to mark even small one-chunk uploaded file as done, Filen returns "Upload chunks are not matching." It would be really helpful if someone told me what this message really means :)

I guess I may have botched either encryption algorithms or file upload process. But encryption algorithms are tested for compatibility with their JS counterparts and should be working, since I can decrypt downloaded files and process metadata successfully. So that leaves upload process as the most probable culprit. 

Current process of file upload is as follows:

### Step 1, encrypt file information, shared by all chunks:
* For now, set parent uuid to the user folder with 'default: true' property.
* Generate new file uuid v4.
* Gather file properties: name, size, last modified, mime type. 
* Generate file key, add it to file properties and encrypt them all as file's metadata.
* Encrypt each file property with file key to their corresponding encrypted strings, also encrypt name with hashFn() for nameHashed.
  * Encryption uses `version` set to 1 everywhere, so it is AES-256 (CBC mode) with Pkcs7 padding.
* Generate upload key and 'rm', whatever it is, to be shared by all chunks.

### Step 2, upload file chunks using file information from step 1:
* Divide file into chunks, with last chunk possibly being uneven. E.g. for a file of size 5 and chunk size 2 chunks would be: [(offset 0, chunk size 2, index 0), (offset 2, chunk size 2, index 1), (offset 4, chunk size 1, index 2)].
* Encrypt each chunk with file key from step 1 and encryption `version` set to 1.
* Post each encrypted binary blob to different random Filen upload server at `/v1/upload?` endpoint, passing the same data from step 1 in URL query params (except for `index`, which is the only different param for each chunk).
* Do not retry to reupload chunks with 'status: false', just fail the entire upload.
* If all chunks resulted in 'status: true' from Filen, send upload key from step 1 to random Filen API server `/v1/upload/done`. 
* Receive "Upload chunks are not matching." Why-y, everything seems analogous to filen-desktop, and yet it fails...

Please pardon my intrusion alongside a wall of text, I am at the wits' end with this one. Anyway, thanks for creating Filen and have a good day.

**Comment by EnoughTea** [comment]
Thanks for your quick and detailed response, I understood it perfectly. Uploading works now, in a sense that uploaded file appears in file manager, albeit broken. If I download uploaded chunk back manually, it will have every byte out of ASCII range replaced by 0xFD. Now that's puzzling; I doubt Filen backend does something with block data. 

Oh well, thanks again :) I'm off to check that correct bytes are actually being sent out and not replaced by http client for some reason.

**Comment by EnoughTea** [comment]
Apparently, it is not Rust, it still me missing something. Here is what I'm doing represented by 3 curl requests. Say I want to create a text file with `Hello, world!`. So I encoded `Hello, world!` to the following bytes: `23 84 20 B0 1E A1 B5 51 BB DA 22 31 DE 19 94 59 27`.

First I post these bytes as chunk 0 (base64-encoded for curl)
```
curl --request POST \
  --url 'https://up.filen.io/v1/upload?apiKey=aYZmrwdVEbHJSqeA0RfnPtKiBcXzUpRdKGRkjw9m1o1eqSGP1s6DM10CDnklpFq6&uuid=32eaff28-ec51-442f-9e5b-4e032cafc9ab&rm=H40x9eW1vYH32xDysYY05WtZziBVtw0G&uploadKey=1i7icHozDMSBkeljsn2nf4fK3CnwsvXP&index=0&chunks=1&name=U2FsdGVkX1%2FKwNtCDcDGfLq4h09Hjlphk1eNyEU9LAo%3D&nameHashed=33d392514cc35587ea22b08009cd99040f6d1648&size=U2FsdGVkX194nX9XaKq3HVYuWt%2BiCcH%2FC0Kov1VZugw%3D&mime=U2FsdGVkX18Yr56rggXgBoFIi%2F61Bt%2BDbAQr5QxKH%2Fc%3D&expire=never&metaData=U2FsdGVkX1%2FRlQN0Qb%2B%2F8tHDOh9iUV4YJMS4KNvk%2BRnfrPRRvFsR4Fi9mvlOrE0TUJr4D0hvMQ9ZTm5yvBhDzvoKCByVfZZ5fS5ExaSevExjbUvaVT6umtrf%2FcVXuX5YkAWZ43eTomANl9ukNMCT3xmgvETCo07N3MDens85LHBTmabiZTuoaMVmu5nGrb5N&parent=cf2af9a0-6f4e-485d-862c-0459f4662cf1&version=1' \
  --data I4QgsB6htVG72iIx3hmUWSc=
```

Then I post empty chunk 1 by omitting body and changing index to 1:
```
curl --request POST \
  --url 'https://up.filen.io/v1/upload?apiKey=aYZmrwdVEbHJSqeA0RfnPtKiBcXzUpRdKGRkjw9m1o1eqSGP1s6DM10CDnklpFq6&uuid=32eaff28-ec51-442f-9e5b-4e032cafc9ab&rm=H40x9eW1vYH32xDysYY05WtZziBVtw0G&uploadKey=1i7icHozDMSBkeljsn2nf4fK3CnwsvXP&index=1&chunks=1&name=U2FsdGVkX1%2FKwNtCDcDGfLq4h09Hjlphk1eNyEU9LAo%3D&nameHashed=33d392514cc35587ea22b08009cd99040f6d1648&size=U2FsdGVkX194nX9XaKq3HVYuWt%2BiCcH%2FC0Kov1VZugw%3D&mime=U2FsdGVkX18Yr56rggXgBoFIi%2F61Bt%2BDbAQr5QxKH%2Fc%3D&expire=never&metaData=U2FsdGVkX1%2FRlQN0Qb%2B%2F8tHDOh9iUV4YJMS4KNvk%2BRnfrPRRvFsR4Fi9mvlOrE0TUJr4D0hvMQ9ZTm5yvBhDzvoKCByVfZZ5fS5ExaSevExjbUvaVT6umtrf%2FcVXuX5YkAWZ43eTomANl9ukNMCT3xmgvETCo07N3MDens85LHBTmabiZTuoaMVmu5nGrb5N&parent=cf2af9a0-6f4e-485d-862c-0459f4662cf1&version=1'
```

Then I post upload done:
```
curl --request POST \
  --url https://api.filen.io/v1/upload/done \
  --header 'Content-Type: application/json' \
  --data '{
	"uploadKey": "1i7icHozDMSBkeljsn2nf4fK3CnwsvXP",
	"uuid": "32eaff28-ec51-442f-9e5b-4e032cafc9ab"
}'
```

Then I download fresh file's single chunk with GET to https://down.filen.io/de-1/filen-1/32eaff28-ec51-442f-9e5b-4e032cafc9ab/0
and get back:
`23 FD 20 FD 1E FD FD 51 FD FD 22 31 FD 19 FD 59 27`
instead of original:
`23 84 20 B0 1E A1 B5 51 BB DA 22 31 DE 19 94 59 27`

Can you see what I did wrong?

**Comment by EnoughTea** [comment]
Yeah, it works; now I feel stupid for missing uploaded byteArray conversion. Oh well, at least that was an easy fix. Again, thanks for your help!

**Comment by EnoughTea** [comment]
Hey people, just letting you know that the first version of Rust API for Filen is now published and this issue can be closed. Crate is somewhat unpolished, full-time job got the better of me, luckily I had time to implement everything needed to write most imaginable tools. Active development phase is complete, but I will keep an eye out for any issues.

**Comment by Dwynr** [comment]
Great work. I'm still impressed you wrote this without any documentation at all. I will make sure to publish this on our website when I can (or maybe fork it to our org's Github). I'm sure this will help a lot of other developers.
