### ISSUE TITLE
[Feature request] File browser integration

### ISSUE THREAD

**Issue by dsommers** [FilenCloudDienste/filen-desktop#150]
Nextcloud and several other services integrates with the native file browser on the OS.  This integration supports both seeing sync status for folders as well as being able to share files and folders without going via any additional app - or the web portal.

A similar feature in Filen would be highly appreciated.

The Nextcloud approach can be seen here: https://github.com/nextcloud/desktop/tree/master/shell_integration.  There are two Linux integrations here, one for KDE (dolphin) and the other one for GNOME Shell (nautilus), as well as both macOS and Windows integrations.

**Comment by Dwynr** [comment]
Yep, next update will merge the web drive UI with the current desktop client UI. Closing for now!
