### ISSUE TITLE
.lnk files ignored (not synced)

### ISSUE THREAD

**Issue by LuckyDuke23** [FilenCloudDienste/filen-desktop#160]
I recognized that .lnk-files are ignored during sync.

I use Parallels 18 and a Windows 10 VM on my MacOS Ventura 13.2 and those .lnk-files are Windows links. These do generally not open in Finder (MacOS) but in the Windows VM where I created and use them as shortcuts. Probably this background info will help to identify the problem.

About 3500 .ink-files where not uploaded to the cloud and consequently not synced to my other devices.

This was also reported to the support and they confirmed to forward the issue to the developers.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-desktop/commit/8123e5f7fa8f0da8e822a4cb52a5018b20191a8a
