### ISSUE TITLE
CPU usage peaks every 60 seconds

### ISSUE THREAD

**Issue by stausmar** [FilenCloudDienste/filen-desktop#162]
### Issue

I'm using the AppImage of Filen.io on Linux. So far, the experience is great, but the CPU usage increases up to 10% every 60 seconds. Usually, the process idles at ~0,1% CPU usage. 

This peak occurrs exactly every 60 seconds and lasts for ~10 seconds. I would assume that the Filen.io client is regularly checking for changes on the file system which is probably the reason for the CPU usage increase.

Problem is that this relatively high increase will increase the CPU fan speed as well which is kind of anoying when the fan speed changes every minute.

Even when the Filen.io client is synchronizing thousands of files, the CPI usage is constantly < 2%.

### AppImage Info

Linux x86_64 - v2.0.16

### System Info

 System:
    OS: Linux 6.1 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 25.82 GB / 31.27 GB
    Shell: 5.1.16 - /bin/bash

**Comment by Dwynr** [comment]
This is due to the Linux implementation manually scanning all local files every 60 seconds. The directory watcher (which normally lets the client know something changed locally before attempting a scan) on Linux does not work in some distributions. We are looking for a fix already.

**Comment by MLBown** [comment]
Can you not use something like select or poll to asynchronously monitor the directories?

https://man7.org/linux/man-pages/man2/poll.2.html

**Comment by MLBown** [comment]
You might be able to use select to monitor the directory for changes asynchronously. It should work with all POSIX compliant operating systems.


https://man7.org/linux/man-pages/man2/select.2.html

**Comment by stausmar** [comment]
Is there any update on this issue?
