### ISSUE TITLE
Mac desktop app window alignment

### ISSUE THREAD

**Issue by azzadrood** [FilenCloudDienste/filen-desktop#163]
Hello,

On the new mac osx 13.2.1 (22D68) the filen desktop app screen is aligned bottom.

![WhatsApp Image 2023-02-17 at 14 07 39](https://user-images.githubusercontent.com/9199523/219649907-e6c5f590-47bc-4146-9400-db9f1a5a65cc.jpeg)

This behavior happened when I enabled mac osx stage manager function.
Now I have disabled the stage manager and restarted the filen app and the issue persist.
Hope this issue helps review and solve the problem!

I'm using filen v2.0.16

**Comment by Dwynr** [comment]
The next major desktop client update will include a new UI based on the web drive, without the tray menu. Closing for now.
