### ISSUE TITLE
Feature Request: Native arm64 desktop app for Apple Silicon M1 devices

### ISSUE THREAD

**Issue by AuthenticPumpkin** [FilenCloudDienste/filen-desktop#17]
Currently there is no option for people who don't use Rosetta2 and need a sync client for our workflow.

Since Apple Silicon is here to stay it would be really helpful to have native arm64 builds for filen desktop.

**Comment by Dwynr** [comment]
We internally develop on Apple Silicon ourselves. Will consider adding a build for ARM64.
