### ISSUE TITLE
Got an error, but it may be something on my side

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-desktop#170]
Got this error:
![изображение](https://user-images.githubusercontent.com/63293432/224503172-1cd39500-3c49-45dd-8f98-79c259a8f6b0.png)
The client wasn't synchronising anything, I don't know what caused the problem and how to reproduce it.
I pressed Continue synchronization and everything appears to be alright again.

**Comment by Dwynr** [comment]
Looks like a temporary networking issue. Will close for now.

**Comment by DanielProg39** [comment]
Got this error half an hour ago
