### ISSUE TITLE
[2.0.16 Windows] .filenignore Edit displaying wrong list

### ISSUE THREAD

**Issue by gwarfjerf** [FilenCloudDienste/filen-desktop#172]
When I open the settings for a Sync, then click on Edit for its .filenignore, it displays the correct .filenignore list for that Sync. However if I close that and open the .filenignore for a different Sync, it will still show me the first .filenignore list. The only way to edit the correct .filenignore list is to exit the app and restart.

![image](https://user-images.githubusercontent.com/34630527/226232447-cf0d7b56-2ed6-434f-b8fd-63ec17590cd9.png)

**Comment by Dwynr** [comment]
Thanks for letting us know, will fix.

**Comment by gwarfjerf** [comment]
awesome, thanks!

May 8, 2023, 05:16 by ***@***.***:
