### ISSUE TITLE
[FR - linux] Can you add back the use of FSwatcher as an advanced settings ?

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-desktop#174]
Can you let advanced user actually enable the FSwatcher instead of the 60sec check ?

Because for user who know that their distribution support it (see the battery be used more due to the checking).
So an "experimental" zone where we can enable the fs watcher with "Warning if your distrib don't support it you may be out of date") can help everyone to be happy, people who don't know what it is (or don't support it have their 60 sec check).

When us who know it work on our distribution can enable it to save battery life.

Thanks in advance.

**Comment by Dwynr** [comment]
Adding back the directory watcher with a fallback to polling in the next update.
