### ISSUE TITLE
[Bug] Gnome 44 - Invisible tray

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-desktop#176]
@Dwynr On Gnome 44 (on fedora 38 silverblue pre-release (use it since more easy to move from version to another)), your app start detect libappindicator, if the gnome extension is here it also add in the tray BUT the icon does not appear, so it's a tray icon invisible (only seen when we hover it).

Screenshot (when hovered totally invisible if not hovered): 

Edit same settings work normally if i rollback to 37 and gnome 43

![Screenshot](https://user-images.githubusercontent.com/42673166/226999061-2cc71391-f1e9-4356-9cce-20bb9efc6083.png)

**Comment by DanielProg39** [comment]
It could be a problem with the Gnome extension, it's not very stable. It could also be due to internal Gnome 44 bugs (since it's a pre-release), or just some extension compatibility issues with a new version of Gnome (which is a fairly common occurrence, so I tend to think that's the case). But that's just my guess

**Comment by BirdInFire** [comment]
> It could be a problem with the Gnome extension, it's not very stable. It could also be due to internal Gnome 44 bugs (since it's a pre-release), or just some extension compatibility issues with a new version of Gnome (which is a fairly common occurrence, so I tend to think that's the case). But that's just my guess

The bug remain on the Fedora 38 stable with Gnome 44

**Comment by DanielProg39** [comment]
Well, I'll try to reproduce this on Fedora 38 too

**Comment by BirdInFire** [comment]
> Well, I'll try to reproduce this on Fedora 38 too

WARNING : if you see /vat/opt or /var/home it's normal since silverblue have a read only system the home folder and other are symbolic link to /var/ to have write access (it's why i have put /var in the .desktop since at first i thinked it was this symbolic link the problem).

My complete config (to have the easiest replication) is fedora silverblue 38 Stable (have this because since the system images are the same on each desktop it's easier to see this kind of bug),

with the gnome extension : AppIndicator and KStatusNotifierItem Support (restart needed after install to work properly)

the appimage is stored in /opt/filen -> the folder is chown at my user name (with the appimage and logo in it (v 2.0.16))

the .desktop is in ~/.local/share/applications and is content is : 

[Desktop Entry]
Name=filen-desktop
Comment=Sync files.
GenericName=Sync
Keywords=Sync
Exec="/var/opt/filen/filen_x86_64.AppImage" %U
Icon=/var/opt/filen/filen.png
Terminal=false
Type=Application
Categories=Network;
TryExec=/var/opt/filen/filen_x86_64.AppImage

**Comment by DanielProg39** [comment]
It seems to be this kind of problem: https://github.com/FilenCloudDienste/filen-desktop/issues/123#issuecomment-1343159057

I also found a way to fix this: [Reddit post](https://www.reddit.com/r/filen_io/comments/1222rqq/managed_to_fix_my_tray_icon_fedora_gnome_linux/)

The author says:

So after the famous update that brought back the tray icon for Linux I never got it to work. I had the extension, tried other ones, posted on here, nothing seemed to fix my issue and bring back the tray icon. Other tray icons were working, which was extra frustrating.

I revised the commit of the introduction of the tray icons and saw that the libappindicator is checked at runtime to either stay as a window or go as a tray icon. After some search I got the library to install for Gnome Shell `sudo dnf install gnome-shell-extension-appindicator -y` and after installing this, the tray icon came back!

Hopefully this works for someone that me that has tray icons but it Filen doesn't seem to want to appear with them.

**Comment by BirdInFire** [comment]
> It seems to be this kind of problem: [#123 (comment)](https://github.com/FilenCloudDienste/filen-desktop/issues/123#issuecomment-1343159057)
> 
> I also found a way to fix this: [Reddit post](https://www.reddit.com/r/filen_io/comments/1222rqq/managed_to_fix_my_tray_icon_fedora_gnome_linux/)
> 
> The author says:
> 
> So after the famous update that brought back the tray icon for Linux I never got it to work. I had the extension, tried other ones, posted on here, nothing seemed to fix my issue and bring back the tray icon. Other tray icons were working, which was extra frustrating.
> 
> I revised the commit of the introduction of the tray icons and saw that the libappindicator is checked at runtime to either stay as a window or go as a tray icon. After some search I got the library to install for Gnome Shell `sudo dnf install gnome-shell-extension-appindicator -y` and after installing this, the tray icon came back!
> 
> Hopefully this works for someone that me that has tray icons but it Filen doesn't seem to want to appear with them.

No the tray is here and fully functional but the filen icon don't show, it's not a tray problem other software do work properly only your appimage have this problem.

**Comment by DanielProg39** [comment]
So, there's some problem with VLC, other applications are shown properly.
Regarding Filen, the dock didn't work, but this:

> sudo dnf install gnome-shell-extension-appindicator -y

helped and now it works as intended.
![Знімок екрана з 2023-04-26 18-07-59](https://user-images.githubusercontent.com/63293432/234621173-4bcb53fa-c30c-4cf9-a42c-4a0ec1695359.png)
