### ISSUE TITLE
[FR] Support Background app running of Gnome 44

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-desktop#177]
Gnome 44 have added a way to show app who run in background, do you think you can check to support it.

**Comment by DodoLeDev** [comment]
I think this feature is only supported by flatpak runtime, so I don't think AppImage will be able to add its entry in it...

**Comment by Dwynr** [comment]
The next major desktop client update will include a new UI based on the web drive, without the tray menu. Closing for now.

**Comment by BirdInFire** [comment]
> The next major desktop client update will include a new UI based on the web drive, without the tray menu. Closing for now.

and like that you just lost a client, tray is a mandatory function for me.

**Comment by Dwynr** [comment]
No it will still have a tray icon. Just the tray window will be reworked.
