### ISSUE TITLE
No 2FA text input field

### ISSUE THREAD

**Issue by ahmuro** [FilenCloudDienste/filen-desktop#187]
Linux x64 lastest RC Appimage on Fedora 38.
When trying to log in, can write email and password, then it asks for 2fa code, but the login fields don't change, so there's no input for the 2FA code and no way to login.

https://user-images.githubusercontent.com/62005324/236710474-ee0c50ef-99f6-4ba6-a461-f4c2561ceaf2.mp4

**Comment by Dwynr** [comment]
Thanks for letting us know. Fixed as per https://github.com/FilenCloudDienste/filen-desktop/commit/c7e21e209b4c57a951949cbc0171c852c8a41a1f.
