### ISSUE TITLE
2.0.20 RC3 stay with some english language

### ISSUE THREAD

**Issue by lyonelf** [FilenCloudDienste/filen-desktop#188]
![image](https://github.com/FilenCloudDienste/filen-desktop/assets/34097487/25d4ca6e-54b4-4cda-a4ac-5f62c9411174)
![image](https://github.com/FilenCloudDienste/filen-desktop/assets/34097487/7a1d372e-6826-4e84-a9fb-6dbc67f43691)
![image](https://github.com/FilenCloudDienste/filen-desktop/assets/34097487/767431be-5830-40e9-90ac-d2bf5e1b0b2b)

**Comment by Dwynr** [comment]
The french translation is missing 50+ strings.

https://github.com/FilenCloudDienste/filen-desktop/blob/master/src/renderer/lib/i18n/lang/fr/fr.ts

**Comment by lyonelf** [comment]
Right, and where are they?
