### ISSUE TITLE
Open source web interface and server

### ISSUE THREAD

**Issue by julianfairfax** [FilenCloudDienste/filen-desktop#19]
Filen is committed to open source, but your web interface and server are still closed source. This means it's not possible to browse the source code of your web interface and server, and only the desktop and mobile apps are open. If Filen were to take this approach, you would be taking an important step forward in open source and privacy for your service. Thank you for all you've done with Filen, and I really hope you consider taking this approach!

**Comment by cwmke** [comment]
Open sourcing the web interface is a higher priority to me since the user clients are performing the encryption. :smiley:

**Comment by BirdInFire** [comment]
instead of this i would prefer simply a third party audit of all the client (desktop, mobile and web), much more productive

**Comment by Dwynr** [comment]
You can inspect all code running in the browser by using devtools. We will consider adding a seperate repo to github containing our webclient's source code. Closing this issue for now.
