### ISSUE TITLE
Empty files (0 bytes) are ignored and when uploading the containing folder on Filen web, cause the folder not to be uploaded at all if no other file that contains something is present

### ISSUE THREAD

**Issue by adorbabble** [FilenCloudDienste/filen-desktop#191]
Hi, I’ve just noticed a new problem with empty files not being uploaded, different from permission errors :

If you have a folder like : 
```
uploadtest/
  iContainNothing.txt (0 bytes)
  iContainSomething.txt (1 byte)
  subfolder/
    emptyFile (0 byte)
```
… and you upload it on Filen web, it will only upload : 
```
uploadTest/
  iContainSomething.txt (1 byte)
```

However, on Filen 2.0.16 for Windows, it will upload `subfolder/` (but not `emptyFile` in there) : 
```
uploadtest/
  iContainSomething.txt (1 byte)
  subfolder/
```

**Comment by Dwynr** [comment]
Expected behaviour.

**Comment by adorbabble** [comment]
> Expected behaviour.

Thank you for your answer, but I don’t think that this behaviour is desirable ? I have seen people complaining on Reddit a few times about the number of folders and files being different on their device and in what Filen saved… it may been because of other sync problems, but still, it makes it difficult to trust the software. When you use a backup program, don’t you expect it to copy exactly the same structure and files except what you have chosen to ignore ? Maybe it could at least be made configurable not to ignore empty files ?

And even if not, a difference in behaviour between the desktop software and an upload on the web should be addressed

Best regards 💜
