### ISSUE TITLE
Linux x64 stuck at login

### ISSUE THREAD

**Issue by ahmuro** [FilenCloudDienste/filen-desktop#193]
1 out of 7 attempts displayed email/password error after about 1 minute when using incorrect credentials, rest of attempts never changed status after 2 or 3 minutes, with either correct or wrong credentials. So either stuck or really slow when checking credentials. Web working fine and status.filen.io correct, so no connectivity issues.

EDIT: This is in lastest RC4

[Screencast from 2023-05-12 21-58-41.webm](https://github.com/FilenCloudDienste/filen-desktop/assets/62005324/db63d09e-89a5-4471-8c59-09c03baf6145)

**Comment by Dwynr** [comment]
Thanks for reporting, will include a fix in the next RC!
