### ISSUE TITLE
[2.0.21] Selective sync checkboxes revert to unchecked

### ISSUE THREAD

**Issue by adorbabble** [FilenCloudDienste/filen-desktop#196]
I’ve just had the automatic upgrade from 2.0.16 to 2.0.21 on Windows 10, and I have one Local to Cloud sync for my documents. In the settings of that sync, when I open the “Configure” settings of Selective sync, all the checkboxes that were checked before the upgrade are now unchecked, and if I try to check them again, they revert to unchecked once I close the Selective sync settings and open these settings again. The files are still uploaded correctly even though the checkboxes appear unchecked

**Comment by Dwynr** [comment]
Just visual, will be fixed. Thanks for reporting!
