### ISSUE TITLE
[2.0.21 Windows] "Issues" panel shows read errors for FeedbackHub/ even though this folder is ignored with .filenignore

### ISSUE THREAD

**Issue by adorbabble** [FilenCloudDienste/filen-desktop#197]
I have a Local -> Cloud sync for my documents on Windows 10, and since upgrading to 2.0.21, Filen shows read errors in the "Issues" panel about a folder called "FeedbackHub". This folder is in `Users/<MyUserName>/Documents` and is part of Windows, used for the "Feedback Hub" application. I have always had this folder ignored in .filenignore, so Filen shouldn’t be displaying these errors. This doesn’t prevent the rest of my files in the sync from being uploaded

**Comment by Dwynr** [comment]
Just visual, will be fixed. Thanks for reporting!
