### ISSUE TITLE
Folders and files with "/" in name not syncing

### ISSUE THREAD

**Issue by hisel-sabermetrics** [FilenCloudDienste/filen-desktop#199]
Hello, I'm using v2.0.22 on MacOS 13.3.1 (a) (22E772610a) with a few synced folder.

Recently, or longer as I haven't checked as detailed previously, I noticed that my folders nested within the sync location does not appear on the cloud drive.

I have created a few test folders and files to test this.

![Screenshot](https://github.com/FilenCloudDienste/filen-desktop/assets/96913686/66d239ae-0a47-4810-b3f8-b2295bf6e6f7)

After relaunching Filen, choose "Force sync" in the menu, I waited for the progress circle to be replaced with "Everything synced".

The result is that nothing appear in the local event log. 
Reloading the cloud drive also does not show the relevant files and folder.

**Comment by Dwynr** [comment]
This is by design to prevent cross-platform sync issues.
