### ISSUE TITLE
[Feature Request] Allowing writing privileges for shared folders

### ISSUE THREAD

**Issue by cwmke** [FilenCloudDienste/filen-desktop#20]
It's great that read-only sharing currently exists but enabling write access would enable me to replace other software I currently use with my family. I'm aware that with the end to end encryption this is considerably more difficult to enable than with other services but hope one day to see it come to filen.

**Comment by Dwynr** [comment]
It's on our roadmap. I will close this issue as it is not really related to the sync client. Will be implemented in the browser version and app in the near future.
