### ISSUE TITLE
Tray icon click on Linux

### ISSUE THREAD

**Issue by tplanner** [FilenCloudDienste/filen-desktop#202]
If the tray icon is clicked on Linux it opens same menu on left and right click. Could it be changed to open "show" option for example on left click?

**Comment by DanielProg39** [comment]
> open "show" option for example on left click

Or if you do left click twice, as I've seen this in several applications

**Comment by Dwynr** [comment]
This is a bug in electron. Will check if they've fixed it yet.

**Comment by Dwynr** [comment]
The next major desktop client update will include a new UI based on the web drive, without the tray menu. Closing for now.
