### ISSUE TITLE
Files with identical names get deleted

### ISSUE THREAD

**Issue by kra-mo** [FilenCloudDienste/filen-desktop#212]
Linux systems allow for files with identical names but differing capitalization.

If Filen encounters such files, it deletes one of them both in the cloud and locally.

This is dangerous, especially with two-way syncing. Ideally Filen would support these files on platforms that support it, but at the very least, it should rename them instead of deletion.

**Comment by onetuser** [comment]
omg, this is huge. Also no removed file with different capitalization in trash.

**Comment by addicted2qubes** [comment]
I think I have had this issue too. I have uploaded many files and noticed 1 or 2 are gone and have not known why. I do not select options to exclude files.

**Comment by Dwynr** [comment]
This is by design to prevent cross-platform sync issues. The web drive and mobile app will also not show files with duplicate names.

**Comment by kra-mo** [comment]
@Dwynr deleting files on the user's computer without asking still seems like a huge issue and I personally cannot have two-way syncing enabled out of fear of this. 

I would still suggest renaming one of the files instead, eg. by adding a ` (1)` suffix.

**Comment by Dwynr** [comment]
They shouldn't be deleted, the client moves files into the .filen.trash.local directory of the sync location and retains them for 30 days.

**Comment by kra-mo** [comment]
That's still not exactly ideal given that it happens without the user's knowledge. You can easily miss something like this, especially the first time you configure a sync.

**Comment by kra-mo** [comment]
@Dwynr This issue is critical to me and I do think data loss should be taken seriously. If you could provide me with the relevant parts of the code, I would be willing to try and fix it myself to rename files instead.
