### ISSUE TITLE
2.0.24 Sync Restart

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-desktop#216]
@Dwynr 

You closed this issue as "Not Planned", but I don't think this can be ignored.

Windows 10 64 bit
Start a large group of files uploading, and then reboot; The upload process starts again from the first file!

This is too taxing on your resources and ours; There must be some tagging done on the local end of the desktop app to prevent this.   Onedrive, Gdrive, and Mega do not show this behavior.

![reboot](https://github.com/FilenCloudDienste/filen-desktop/assets/105058921/be454020-5d08-41e7-97ac-5e0cd90fafc0)
![4105 left](https://github.com/FilenCloudDienste/filen-desktop/assets/105058921/58721ece-a442-4dc4-83d1-c87ed1aaa468)

**Comment by telrod11** [comment]
So, just FYI, the only way you can ever complete a large group of files, is to leave the PC up, or use hibernate or standby.   Apparently, 2.0.24 has no "flag" to realize where it might be in the upload process, but windows can capture what is happening and restore it, if a full reboot is not requested.

**Comment by Dwynr** [comment]
Next update should fix the issue. Thanks for reporting.
