### ISSUE TITLE
[BUG] Files with 0 KB are not synced

### ISSUE THREAD

**Issue by RocoByte** [FilenCloudDienste/filen-desktop#219]
If I create a file, e.g. a .txt file, but do not write anything into it, i.e. it has 0 KB, it is not synced to the cloud.
So if I have a project where I create an .examplefile which I need for something, whatever, it will not be synced because it has 0 KB.

Tested under Windows 11:
_Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36_

**Comment by Dwynr** [comment]
This is not a bug and by design. Might change in the future, but for now 0 byte files are not supported.
