### ISSUE TITLE
[Feature request] ARM build for Mobile Linux

### ISSUE THREAD

**Issue by julianfairfax** [FilenCloudDienste/filen-desktop#22]
Filen is a great free and open source cloud storage service, and while I don't usually like the concept of AppImages, I think it works with no problems here. However, there's no ARM build for the AppImage, meaning you can only use it on a desktop Linux computer. Please include an ARM version in your future builds of the AppImage for Linux. Thank you for what you've done with Filen!

**Comment by Dwynr** [comment]
Will look into this.
