### ISSUE TITLE
[BUG] Program crashes when logging out on Windows 7

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-desktop#229]
Hello!

_Yeah, I know, I'm one of those die-hard Windows 7 users._

But strangely, only on this platform (it doesn't appear on Windows 10, at least for me), when I am logging out of my computer, this error message appears and prevents my PC from shutting down:

![Error message on log out](https://github.com/FilenCloudDienste/filen-desktop/assets/59477313/c5b895bc-b829-4be3-b73e-17e73497bc23)

**Comment by Dwynr** [comment]
Probably an issue with electron's built in power-manager API. We will update our electron dependency in the next release, which might fix it. Otherwise I will come back and further investigate.
