### ISSUE TITLE
[Bug] - Reinstalling filen is already logged in with previous session

### ISSUE THREAD

**Issue by vishnucoder1** [FilenCloudDienste/filen-desktop#233]
OS: Mac Intel

How to reproduce

- Install Filen desktop
- Login using filen account
- Uninstall Filen
- Install Filen again
- Launch Filen. The previous account is already logged in

Expected: Filen should ask for login credentials again after reinstall. The uninstall should be clean.

**Comment by Dwynr** [comment]
By uninstalling the app on macOS you probably mean dragging the "Filen" app from the Applications folder into the trash? Yea this will not clean up the user preferences which are stored elsewhere. Unfortunately there is no hook for the client to know that it's being deleted on macOS. If you want to clear sessions and preferences, you can delete the folder at _~/Library/Application Support/filen-desktop_
