### ISSUE TITLE
data deletion policies should be lined out in TOS

### ISSUE THREAD

**Issue by RalMay** [FilenCloudDienste/filen-desktop#238]
Hi,

[TOS](https://filen.io/terms) do not reflect the data deletion policies for overused plans and "lifetime" plans that you described in your last [status update](https://blog.filen.io/statusupdate-21-02-2023/).
As (only the) TOS are part of the contract this should be changed.

**Comment by Dwynr** [comment]
GitHub is not the place for questions like this. 

(everything is already in the ToS)
