### ISSUE TITLE
Broken on Fedora 35

### ISSUE THREAD

**Issue by Fossium** [FilenCloudDienste/filen-desktop#24]
Hi,

The Linux client doesn't work for me on Fedora 35. The first time I run it, it doesn't show a GUI at all, however top shows it running in the background. The second time I run it, the UI shows up, but disappears as soon as I click anything outside the window, though it still seems to be running in the background. I've included the main.log for both runs, but they don't appear to show any issue.

[first.log](https://github.com/FilenCloudDienste/filen-desktop/files/7764166/first.log)
[second.log](https://github.com/FilenCloudDienste/filen-desktop/files/7764167/second.log)

**Comment by cwmke** [comment]
Hi @Fossium. Do you have a [Gnome shell extension](https://extensions.gnome.org/) installed that shows tray icons similar to the screenshot below? Filen's UI is accessed with a right click on the tray icon so without an extension Filen is inaccessible with Gnome.

![image](https://user-images.githubusercontent.com/1923967/151709505-d2fcfe49-f8f1-4a71-8441-a175e4f2f293.png)

**Comment by Loki-L1130** [comment]
It is an AppImage, I think you can use [AppImage Launcher](https://github.com/TheAssassin/AppImageLauncher) so that it integrates the AppImage into the system for the Tray Icon. Might be Possible. Give it a try.

**Comment by Fossium** [comment]
Thanks, it works now after installing https://extensions.gnome.org/extension/2890/tray-icons-reloaded/
It would probably be a good idea to add a note about this in the readme and on the website.
