### ISSUE TITLE
[Feature request] Local Webdav secure (https) and creds.

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-desktop#25]
I would like to ask if you can make a function to enable locally (127.0.0.1 and/or ::1) Webdav to let us actually sync our bookmark with floccus and/or password from password manager who support webdav sync (keepass etc).

Like that we can use them securely in E2E cloud.

**Comment by Dwynr** [comment]
Will be possible as soon as we integrate rclone into our platform. This will happen in a seperate repo. Closing.
