### ISSUE TITLE
Content of some subdirectories from Mac directories are not being synced

### ISSUE THREAD

**Issue by amarendra** [FilenCloudDienste/filen-desktop#255]
I am syncing the entire `~/Pictures` Mac folder to a Filen remote folder in "local backup" sync mode. 

Inside it there is a folder `Photos Library.photoslibrary` that does show inside the remote folder but it has no other files folders synced inside it. It just shows `No files or folders uploaded yet`.

`~/Pictures` has other sub folders, including a very similar sub-folder `Photo Booth Library` folder, and these get synced as expected.

I have tried pausing and resuming the sync. Adding the `~/Pictures` folder sync again after removing. Nothing works. I have not added any kind of exclusion config either.

Unsynced `Photos Library.photoslibrary` folder:
<img width="990" alt="Screenshot 2023-12-02 at 11 19 02 AM" src="https://github.com/FilenCloudDienste/filen-desktop/assets/79829/d99c07f9-f43e-4738-b1a2-f3ffe9c7c69a">

Correctly synced `Photo Booth Library` folder:
<img width="1062" alt="Screenshot 2023-12-02 at 11 19 22 AM" src="https://github.com/FilenCloudDienste/filen-desktop/assets/79829/489487e8-00aa-443f-95cf-8ca65d8ad9cb">

**Comment by amarendra** [comment]
I believe this issue is critical. Because I am not getting any error or warning or anything information that might suggest something is not getting synced. It shows completely synced. That means I am not sure we can trust the app to sync everything.

**Comment by Dwynr** [comment]
Files inside the proprietary macOS photo library folders are not directly exposed to other programs reading those libraries. Unless we find a hacky workaround there is no way to read it with normal system calls (.readdir).

**Comment by amarendra** [comment]
@Dwynr 

They have faced similar issues here https://github.com/borgbackup/borg/issues/5303

Or is it related to Filen desktop app permissions by any chance? Anyway, have you folks explored it? Mac users will have that as a very important use case because that is how iCloud photos are saved on Mac and that is the way to backup those files.
