### ISSUE TITLE
add compression support

### ISSUE THREAD

**Issue by lucamp** [FilenCloudDienste/filen-desktop#29]
Hi,
filen does not compress files at all before sending or receiving.
For instance, this is pretty noticeable with a slow upload connection and highly compressible files.

Just for debug try hgt DEM data available at [viewfinderpanoramas.org](http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm)

- Download M32.zip (Germany central)
- unzip M32.zip
- as reference, use N48E006.hgt

uncompressed size = 2.9 MB
7z compression = 913 kB
pgp encrypted = 1.3 MB

Traffic generated by all those hgt files (24 files, 69.2 MB) it's equal to their uncompressed size or even more (roughly monitored with gnome-system-monitor). 

Please consider implementing compression in a way to reduce traffic bandwidth

**Comment by Dwynr** [comment]
Compression is not possible. Or well rather not really efficient when using with client side end to end encryption. We decrypt files on the fly on the clientside. Not all devices are fast enough decrypting + decompressing at the same time (this applies to mobile and browsers).
