### ISSUE TITLE
Notification prompt in case of a New release & Post Things after update

### ISSUE THREAD

**Issue by Loki-L1130** [FilenCloudDienste/filen-desktop#3]
- When there is a New Update in Desktop App for Windows it Shows New Version Available Click to Update Prompt using the native Notification via Action Center of Windows 10. While showing show it comes with a tiltle Filen.Electron&__________ and some random codes in it. 

- I do got that as the App is totally based on Electron so it is showing like that but it would be Great if it just shows just Filen Desktop.

- After clicking to Update from the notifications the app updates, reopens & Just showing the Filen Logo gets stuck for sometime. To make the App work need to exit by right-click menu and reopen it. And it just works flawlessly.

Note : The First two are things I remember when I updated the App about 2 weeks ago for the Version 1.5.0 .

**Comment by Loki-L1130** [comment]
@Dwynr I think that you need reopen this issue. This is what I need to tell you (Just got a Snap of it). Just Try to Change this like Tutanota do for their Electron based Desktop App. and also please add an Option to like "Click to Update" Banner as in Tutanota Desktop App.

![Snap 18](https://user-images.githubusercontent.com/87981739/135216211-fa6f2c67-37af-405c-9b35-e8c70a11baf6.png)

**Comment by itsmeboy0** [comment]
> @Dwynr I think that you need reopen this issue.

Yep, didn't get notified of the release made just earlier so I came to look for the issue here.
