### ISSUE TITLE
Empty files (0 b) not synced or removed from web client

### ISSUE THREAD

**Issue by nenadandric** [FilenCloudDienste/filen-desktop#32]
When you have file synced, and changed it to be 0b size (e.g. delete all text from the document), it is deleted from web client.

**Steps to reproduce**
* Create new text file and add some text (or copy existing one to sync folder)
* File is synced to web client/server
* (Optional) Edit file to create new version
* Remove all text from file -> File is deleted from web client, but remains on local storage
* Add again some text -> File is again created in web client, but without history (as completely new one)

Old file is in Trash, and can be restored only if local file is still empty. If it is changed and synced again, it can not be restored, and versioning becomes broken

**System**
Desktop client: Linux (AppImage) 1.6.2
OS: openSUSE Tumbleweed + KDE Plasma 5.23.5

**Comment by Dwynr** [comment]
Will look into this.
