### ISSUE TITLE
[Feature Request] Show sync progress and language support

### ISSUE THREAD

**Issue by KDropZ** [FilenCloudDienste/filen-desktop#33]
In the Desktop app it would be great if it shows the progress of the new files that are being synced. At the moment it's just showing "Filen is synchronizing"

Example:
Putting 6 new files into the sync directory.
Clicking on the Filen.io Icon in the taskbar.
Program showing upload and sync progress of each new file added (e.g. as seen in Dropbox)

Also it would be great if different languages would be supported on the desktop version as they are on mobile.

**Comment by DodoLeDev** [comment]
Hi!
I agree with you, and I've just proposed a concept which integrates it: #38

What do you think? 😋
