### ISSUE TITLE
[Wayland] Native support

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-desktop#35]
Is it possible make an update to allow on wayland desktop to actually use Wayland instead of Xwayland,
Xwayland is automatically used when an app without support for Wayland is launched, updating electron (or any other tool) to last version (who support wayland) generally fix the problem.

I ask this because Xorg is know to have old misconception from the start who can cause security issue and since you are one of the best at security, i think this problem must be fixed as soon as possible.

**Comment by Dwynr** [comment]
New desktop client includes the latest electron version, should be fixed then.
