### ISSUE TITLE
App Image not Working on LXDE, Debian 11

### ISSUE THREAD

**Issue by larry77** [FilenCloudDienste/filen-desktop#36]
I summarize here the discussion I had with the support team.
The app crashes on Debian 11 + LXDE.

Here is the log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.16
3 info using node@v14.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle filen-desktop-client@1.6.2~prestart: filen-desktop-client@1.6.2
6 info lifecycle filen-desktop-client@1.6.2~start: filen-desktop-client@1.6.2
7 verbose lifecycle filen-desktop-client@1.6.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle filen-desktop-client@1.6.2~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/lorenzo/filen-desktop-master/node_modules/.bin:/home/lorenzo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/lorenzo/Telegram/:/home/lorenzo/julia-1.7.0/bin
9 verbose lifecycle filen-desktop-client@1.6.2~start: CWD: /home/lorenzo/filen-desktop-master
10 silly lifecycle filen-desktop-client@1.6.2~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle filen-desktop-client@1.6.2~start: Returned: code: 7  signal: null
12 info lifecycle filen-desktop-client@1.6.2~start: Failed to exec start script
13 verbose stack Error: filen-desktop-client@1.6.2 start: `electron .`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid filen-desktop-client@1.6.2
15 verbose cwd /home/lorenzo/filen-desktop-master
16 verbose Linux 5.10.0-11-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v14.19.0
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 7
22 error filen-desktop-client@1.6.2 start: `electron .`
22 error Exit status 7
23 error Failed at the filen-desktop-client@1.6.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]

Really looking forward to the next release ASAP because I really see plenty of issues with the Linux desktop and the app is now unusable for me. 
To be fair and straight, MEGA has a linux app, properly packaged as a deb file, which has never given me a fraction of this headache.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-desktop/issues/57
