### ISSUE TITLE
"Filen Sync Helper (Renderer)" causes high CPU on Mac

### ISSUE THREAD

**Issue by alex-irschfeld** [FilenCloudDienste/filen-desktop#41]
Hi!

It seems like the "Filen Sync Helper (Renderer)" causes running high CPU on Mac.
Is this a known issue or could some third party apps causing this problem?

Many thanks in advance.
(Love the design of Filen and its simplicity!)
Cheers

**Comment by EdwardLangdon** [comment]
Well, They are currently working on New Desktop Apps. So, Let's better wait for it.
