### ISSUE TITLE
Support for crypto payments?

### ISSUE THREAD

**Issue by tuqueque** [FilenCloudDienste/filen-desktop#44]
Hello... I've been looking for alternatives to MEGA and I just found this service... It looks almost perfect!... Linux support, client-side encryption, very affordable plans... But the deal breaker (for me), no support for payment with cryptocurrencies.

Any plans to implement that (preferably in the near-ish future)?

Thanks in advance.

**Comment by tuqueque** [comment]
> There is support but only for lifetime plans

Oh, I didn't notice that!... Lifetime plan is even better!... Now, I just see a 100GB plan, but they mention "Lifetime plans can be stacked."... What does that mean?... Can I buy like a 300GB lifetime plan? How?

**Comment by doubletimedan** [comment]
If you wanted 300gb of space for example you can buy the starter lifetime 3 times on the same account which will stack 3 times
