### ISSUE TITLE
Crash when clicking "Upload files" or "Upload folders" on KDE

### ISSUE THREAD

**Issue by duhast** [FilenCloudDienste/filen-desktop#45]
**Describe the bug**
The desktop app silently crashes when clicking "Upload files" or "Upload folders" in the tray context menu.

Same happens when trying to configure sync folders from the "Settings" tab.

**To Reproduce**
1. Run AppImage on Fedora KDE
2. Login
3. Open tray context menu
4. Click "Upload files" or "Upload folders"

**Expected behavior**
It is expected a file/folder open dialog to appear to allow choose local folder where cloud files should be synced from.

**Screenshots**
![image](https://github.com/user-attachments/assets/5e72327b-a874-4e6b-9010-ce90e99b9bfd)

**OS (please complete the following information):**
 - OS: Fedora 40 KDE spin
 - Hardware configuration: ASUS ROG Zephyrus M16 laptop, Intel Core i9, 40 Gb RAM
 - Filesystem and Disk type used: NVMe SSD with btrfs filesystem
![image](https://github.com/user-attachments/assets/58704821-b23a-416b-a8df-909629e9ee27)

**Additional context**
N/A

**Comment by Dwynr** [comment]
This is the wrong repository. You are using the legacy client which will soon be deprecated in favor of the new client (this repo, which is currently in beta).
