### ISSUE TITLE
Add support for specifying multiple backup folders for Filen desktop client

### ISSUE THREAD

**Issue by meyou69** [FilenCloudDienste/filen-desktop#47]
Hello,

I would like to request a new feature. Currently, the Filen desktop client only allows me to synchronize files from the "Filen Sync" folder under my home directory. Thankfully I can change this functionality to any directory of my choice but I think this is not enough.

What I wish to propose is to allow the user to configure as many backup directories as he or she wishes, each pointing to different directory paths on the file system, and even, more importantly, a backup schedule configuration for each of them, in which the user can configure whether the synchronization should happen all the time automatically (the default option) or whether it should only run on demand or at a specific schedule (i.e. daily, weekly, monthly etc.).

This latter feature is very important to me because, on my Linux machine, I have a Veracrypt encrypted partition that I need to be backed up. However, this directory is under its own partition, separate from my home folder (so I would need to add it as a separate backup folder, distinct from my usual home backups) and, even more importantly, this partition is only mounted once I manually unlock it in Veracrypt (I have to manually enter the decryption passphrase for this to happen). Thus, I need to be the one to initiate the sync for this particular folder, only once I decrypt and mount that partition. If the desktop client is not aware of this, it would try synchronizing this folder on a partition that's not even mounted and then realize that there's nothing to synchronize from and nowhere to synchronize to.

**Comment by Dwynr** [comment]
Syncing multiple individual folders of the user's choice will be available in the new version.
