### ISSUE TITLE
Update installers

### ISSUE THREAD

**Issue by arekscode** [FilenCloudDienste/filen-desktop#51]
The latest version of the installers is 1.6.2, whereas the repo is on version 2.0.1. 

Given the privacy focus of this service, vulnerabilities should be fixed where possible (NPM reports 11 high and 11 medium vulnerabilities with commit [71eaac4](https://github.com/FilenCloudDienste/filen-desktop/commit/71eaac40f2e4070f4cf42da078c452ae240a77c2)), and new installers/executables should be published. 

I believe that would close #47, #36, and #13.

**Comment by Dwynr** [comment]
Version 2 of the desktop client will be release as soon as it is completely stable. It's still under beta testing.
