### ISSUE TITLE
Linux app issues

### ISSUE THREAD

**Issue by julianfairfax** [FilenCloudDienste/filen-desktop#56]
The Linux app opens a full app in the dock that can be closed by right-clicking on it and selecting quit, but the show option from the tray will then no longer work to show it and you can't have the app start on boot any more since that option is not in the settings. Wil these issues be fixed at some point?

**Comment by Dwynr** [comment]
Those are not issues. Since **alot** of linux distributions do not fully support electrons way of integrating into the tray icon bar, we decided to make the client openable and closeable from the task bar instead, as a standalone window. 
Auto starting app images on boot is not possible with the current code. You would have to use something like AppImageLauncher.

**Comment by julianfairfax** [comment]
Auto starting it used to be an option though. Why was it only now removed. Can there be an option to not show it as a stand-alone always open window in the settings for distributions that do support the tray icon?

**Comment by Dwynr** [comment]
Yea I can consider adding a manual option for enabling the tray icon.
Regarding the auto start on Linux we have to research it a bit more.

**Comment by julianfairfax** [comment]
The tray icon already shows up, but you just can't stop the app window from always running. So it'd be nice if that was an option, like before.

**Comment by Dwynr** [comment]
Oh yea true, will add an option for that on linux.

**Comment by trymeouteh** [comment]
Same issue, when I launch File, the tray icon appears in my tray with the syncing window opening. I can close the syncing window but when I click on the tray icon and click "Show", it will not ope up the syncing window. Very annoying.

Would also like a setting to have the syncing window not open when you launch Filen.

**Comment by joshuarcase** [comment]
On version 2.0.10 I no longer have the tray icon. Also, after choosing quit it continues to run in the background.
