### ISSUE TITLE
Versioned releases

### ISSUE THREAD

**Issue by ubmarco** [FilenCloudDienste/filen-desktop#56]
**Is your feature request related to a problem? Please describe.**
The website https://filen.io/apps/desktop lets me download binaries for the desktop applications such as `Linux (64 bit) (AppImage)`. However it's not a versioned download. That's a problem for downstream package managers as they can't refer specific upstream releases. For Arch, there's an AUR package https://aur.archlinux.org/packages/filen-desktop-appimage which is outdated due to this.
I see there are releases on Github https://github.com/FilenCloudDienste/filen-desktop/releases however the latest version `2.0.24` is not contained.

**Describe the solution you'd like**
Download links for recent versions with version identifier in the URL.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot from AUR comment that shows the problem. The linked issue https://github.com/FilenCloudDienste/filen-desktop/issues/64#issuecomment-1214949510 does not exist anymore unfortunately..
![image](https://github.com/user-attachments/assets/b6ee87ed-23ad-4c2f-a961-13196d23b1e5)

**Comment by ubmarco** [comment]
Last versioned release available is
https://cdn.filen.io/desktop/release/v2.0.22/filen_x86_64.AppImage

The link
https://cdn.filen.io/desktop/release/v2.0.24/filen_x86_64.AppImage
returns a 404.

**Comment by Dwynr** [comment]
We will start providing versioned downloads with our new desktop client (this repo, the current one has been deprecated) as soon as we release it publicly. Due to our new CI/CD pipeline, releases will also be available through GitHub.
