### ISSUE TITLE
Again App not Working on LXDE Debian 11

### ISSUE THREAD

**Issue by larry77** [FilenCloudDienste/filen-desktop#57]
Hello,
This is a follow up of https://github.com/FilenCloudDienste/filen-desktop/issues/36 .
I downloaded the new image for Linux and I ran it.
I set up my sync point this way: on my pc it is the /filen_sync file in my home directory, which is what I have always used in the past.
This directory synchronizes to the online folder "Filen Sync" under "Cloud Drive", so I selected "Filen Sync" as the online folder.
However the client appears to go on forever looking for changes (it always tells me "Checking changes")
I paste below what I see in my shell (if you need some logs, please tell me how to retrieve them).

`$ ./filen_x86_64.AppImage 
00:46:17.329 › Checking for update
00:46:17.335 › Checking if an update is available
00:46:17.336 › Initializing startup windows
[38399:0804/004617.570204:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
00:46:17.887 › Socket connected
00:46:17.955 › Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
00:46:17.956 › No update available: {
  version: '2.0.1',
  files: [
    {
      url: 'filen_x86_64.AppImage',
      sha512: '5S2g2gy4ZlMhuoVle3BmwHk2ekFPHUyOQnOWlCYpwXMbsL1gUFbwkudCX/fVx7+RXssy6BhX/d6EOzOvu1aByQ==',
      size: 147455109,
      blockMapSize: 150681
    }
  ],
  path: 'filen_x86_64.AppImage',
  sha512: '5S2g2gy4ZlMhuoVle3BmwHk2ekFPHUyOQnOWlCYpwXMbsL1gUFbwkudCX/fVx7+RXssy6BhX/d6EOzOvu1aByQ==',
  releaseDate: '2022-08-01T21:28:33.447Z'
}
00:46:18.519 › Init startup windows done
00:46:18.890 › Sending socket auth
00:51:17.338 › Checking for update
00:51:17.340 › Checking if an update is available
00:51:17.613 › Update for version 2.0.1 is not available (latest version: 2.0.1, downgrade is disallowed).
00:51:17.613 › No update available: {
  version: '2.0.1',
  files: [
    {
      url: 'filen_x86_64.AppImage',
      sha512: '5S2g2gy4ZlMhuoVle3BmwHk2ekFPHUyOQnOWlCYpwXMbsL1gUFbwkudCX/fVx7+RXssy6BhX/d6EOzOvu1aByQ==',
      size: 147455109,
      blockMapSize: 150681
    }
  ],
  path: 'filen_x86_64.AppImage',
  sha512: '5S2g2gy4ZlMhuoVle3BmwHk2ekFPHUyOQnOWlCYpwXMbsL1gUFbwkudCX/fVx7+RXssy6BhX/d6EOzOvu1aByQ==',
  releaseDate: '2022-08-01T21:28:33.447Z'
}`

Any idea what the issue is?
Thanks

**Comment by larry77** [comment]
Further to that: apparently the issue is dri3 not being supported by my system. To be fair, until now I even did not know what dri3 was. I can use gpu for computing and my dropbox and megasync apps work like a charm, so this should not be a make it or break it requirement for the filen app.

**Comment by larry77** [comment]
I add another piece of information. I have nvidia proprietary drivers installed from debian contrib/non free. I need them for gpu computing applications.
From what I understood, "DRI2" in the xdpyinfo output is just what the driver reports when queried through the DRI protocol but the protocol itself is not used, because the proprietary drivers take care of that.
Once again, I cannot be the only one using nvidia drivers under linux and it is not a problem for any other (including file synchronization) apps on my system.

**Comment by DodoLeDev** [comment]
A simple workaround to this issue could be adding a `--disable-gpu` flag to the filen app in order to disable hardware acceleration... :man_shrugging:

**Comment by larry77** [comment]
Well, I just know that release 2.0.2 did not solve my problem...

**Comment by larry77** [comment]
> A simple workaround to this issue could be adding a `--disable-gpu` flag to the filen app in order to disable hardware acceleration... man_shrugging

Any chance to see this flag implemented in the near future?

**Comment by larry77** [comment]
Or in the not so near future? It has been months by now!
