### ISSUE TITLE
Explain Account Recovery Process in Detail 

### ISSUE THREAD

**Issue by Loki-L1130** [FilenCloudDienste/filen-desktop#6]
According to Filen Security Whitepaper,

> Since the user’s password is the root of all client-side encryption, forgetting it results into the inability to decrypt the user’s data, which will make it impossible for either Filen or the user to recover the data stored on the user’s account.
> 
> **If the user is still logged in on a different device, he can change his password**. Changing the password will generate a new master key as explained in the registration process. This master key is then appended to the old master key, encrypted and sent to the API. Filen never stores unencrypted keys. Filen calls this master key chaining. This process makes decrypting data encrypted with the old master key possible, while new data is encrypted using the new encryption key.

According to Boldly marked words this mechanism similar to What Sync.com does but there is no such Option visible in the Settings of the App.

**Comment by Dwynr** [comment]
You can only reset your password using the web file manager currently.
