### ISSUE TITLE
Add AppImage back to release assets

### ISSUE THREAD

**Issue by lagerfeuer** [FilenCloudDienste/filen-desktop#64]
I am the creator and maintainer of the `filen-desktop-appimage` package[1] in the Arch User Repository. The latest 2.x.x releases are missing the packaged desktop app. I was using the AppImage attached to every release as the base for my AUR package (as a way to pin the version).

Would it be possible to have them added back to every release? Or is there a directory with versioned artifacts somewhere else? I just need a way to fetch the versioned AppImage, not just the latest one.

[1] https://aur.archlinux.org/packages/filen-desktop-appimage

**Comment by DodoLeDev** [comment]
Well... It seems that the AppImage you are looking for is now located to a unique URL path: https://cdn.filen.io/desktop/release/filen_x86_64.AppImage

I think it could be easier to use this new source URL as it remains the same when there is a new update available!

**Comment by lagerfeuer** [comment]
I understand that I can get the _latest_ version that way. But that's against the [package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_versioning).
For example, version 2.0.2 of `filen-desktop-appimage` needs to reliably download and install the AppImage version 2.0.2.
The package cannot download the latest version. It needs to be able to pin to a certain version to allow updating on new version and even downgrading to previous versions.

I hope this clears things up a bit.

**Comment by DodoLeDev** [comment]
Ahhh okaaayyy! It's clear! 👌🏻

**Comment by Dwynr** [comment]
Understandable, great that the community maintains repos.

From now on, older releases will be available at

https://cdn.filen.io/desktop/release/VERSION/filen_PLATFORM_ARCH.EXT

For 2.0.2 that would be https://cdn.filen.io/desktop/release/2.0.2/filen_x64.exe

Our inbuilt update allows no downgrades though, so older version will update to the latest one automatically.

**Comment by lagerfeuer** [comment]
That's exactly what I needed, thanks!

**Comment by lagerfeuer** [comment]
@Dwynr Any chance you could also make the latest version available under a versioned link? Otherwise, I'm always trailing by one version. The package I'm maintaining has to use a link in the form of: `https://cdn.filen.io/desktop/release/${pkgver}/filen_${arch[0]}.AppImage`
