### ISSUE TITLE
Filen 2.0.24 does not start on Catalina 10.15.7

### ISSUE THREAD

**Issue by avcodex** [FilenCloudDienste/filen-desktop#70]
**Describe the bug**
Filen 2.0.24 does not start on Catalina 10.15.7

**To Reproduce**
Try to start the application 

**Expected behavior**

Start applivation

**Screenshots**

**OS**
 - OS: Catalina 10.15.7
 - Mac Book Pro Retina

**Comment by Dwynr** [comment]
2.0.24 will be deprecated as soon as we release the new client which is in beta right now.
