### ISSUE TITLE
Linux startup support

### ISSUE THREAD

**Issue by Terkyz** [FilenCloudDienste/filen-desktop#72]
On Linux I see no way to make the Filen client start as soon as I start my machine, and I did it manually using Stacer but it always starts the sync window in the foreground instead of going to the tray, and it has a slight impact on the use of CPUs.

Do you plan to add the option to boot with the system in Linux?

**Comment by Dwynr** [comment]
Since the Linux version is an AppImage we usually recommend using something like AppImageLauncher to launch it on startup, since the AppImage cannot launch itself (due to being mounted to tmp directories on start).
