### ISSUE TITLE
over-and-over re-syncing whole syncs that contain 1+ hard-failed files

### ISSUE THREAD

**Issue by RalMay** [FilenCloudDienste/filen-desktop#75]
**Describe the bug**
When a sync contains even a single file where the name (incl. path) is too long (Ignored-Tab: "File or directory path too long") then _all_ files (even 10k+ files) from said sync are _all_ synced over and over and over.

**To Reproduce**
1. Create a folder tree of 'too much' depth containing a file 
2. put some files in tree root
3. Create a sync
4. watch Events-tab of said sync - _all_ files are synced over and over and over 

**Expected behavior**
Ignore hard-failing files, especially don't try to re-sync all files when only a few failed

**Screenshots**
![Settings](https://github.com/user-attachments/assets/14f80bf6-3dc0-4931-b7ce-e1bcdc35ee02)
![Events](https://github.com/user-attachments/assets/baaaefe3-bae0-4a36-a776-0e880dd1e54b)
![Ignored](https://github.com/user-attachments/assets/662f6159-200e-4532-9358-4802172db59a)
![Issues](https://github.com/user-attachments/assets/9f9653d4-ac67-44bf-a3c0-acd385c20943)

**OS (please complete the following information):**
 - OS: W10x64 v.10.0.19044.3324 (VM in Proxmox 8.2.4.)
 - Hardware configuration: 6 Cores of R5 5600U, 16 GB, 32 GB SSD
- SSD, NTFS

**Comment by RalMay** [comment]
addendum: same behavior at least since v3.0.21-rc4

**Comment by Dwynr** [comment]
Thank you for reporting, will look into it.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-sync/commit/b3ac80f3b05c25626df7588eee5aa61070e5384e
