### ISSUE TITLE
Support for empty files?

### ISSUE THREAD

**Issue by superDuperCyberTechno** [FilenCloudDienste/filen-desktop#75]
On Linux, the client never syncs empty files. Will this be implemented in the future?

**Comment by Dwynr** [comment]
We are currently not planning on supporting 0 B file uploads.

**Comment by superDuperCyberTechno** [comment]
Sad to hear it. A deal-breaker for me. Hope to see it in the future...

**Comment by AIGeneratedUsername** [comment]
@Dwynr May you add a warning somewhere to the GUI to let a user know that a file will not be synced?

I decided to test your app, and then I almost removed it thinking that it is stupid and can not even sync files, but then I found this issue.
