### ISSUE TITLE
Network drive on Windows 11 does not handle correctly the # character in filename.

### ISSUE THREAD

**Issue by Narziss70** [FilenCloudDienste/filen-desktop#76]
**Describe the bug**
Network drive on Windows 11 does not handle correctly the # character in filename.

**To Reproduce**
Open Filen drive on Windows File Explorer (X:), go to any folder where files containing the # character is present in file name, the file is not listed. The files are present in the Filen Windows client.

**Expected behavior**
Files should show up in Filen drive on Windows File Explorer just like they show up and sync on the client

**Screenshots**
![Filen io client](https://github.com/user-attachments/assets/ead8141f-4cba-4a6c-84fe-abc4ad7e31f0)
![Windows explorer](https://github.com/user-attachments/assets/3b8ca120-d4b7-4f54-8b45-896f3d1cdb5d)

**OS (please complete the following information):**
 - OS: [e.g. Windows, macOS, Ubuntu]
Windows 11 Pro 24H2
 - Hardware configuration [e.g. CPU, RAM, DISK]
 - AMD Ryzen 5 5500U with Radeon Graphics            2.10 GHz, 8 GByte, SSD
- Filesystem and Disk type used [e.g. SSD, NTFS, ext4]
SSD, NTFS Bitlocker encrypted.
**Additional context**

**Comment by Dwynr** [comment]
Thanks for reporting. 

Fixed via: https://github.com/FilenCloudDienste/filen-webdav/commit/ea07171bef26f338460482df03ef3da774b640f9

**Comment by Narziss70** [comment]
I confirm it looks fixed. Thanks!
