### ISSUE TITLE
Selective Sync missing from v3

### ISSUE THREAD

**Issue by godzfire** [FilenCloudDienste/filen-desktop#77]
**Describe the bug**
On version 2.x, under Settings > Sync > [any example sync] cogwheel icon, one of the options is Selective Sync, which when you click Configure next to it, it allows you to specifically choose which files/folders you want to sync. This functionality is missing in version 3.x including the most current dev release 3.0.23.

**To Reproduce**
Listed above

**Expected behavior**
Option for Selective Sync exists

**Screenshots**
Version 2
<img width="431" alt="image" src="https://github.com/user-attachments/assets/5d34f2a5-138b-4124-bd49-2d3bd9b06ccf">

Version 3
<img width="1028" alt="image" src="https://github.com/user-attachments/assets/74af5ade-32f4-4ad9-bbb3-cc726f7c7e64">

**OS (please complete the following information):**
Mac OS Monterey 12.7.6 (21H1320)

**Comment by Dwynr** [comment]
Selective sync is not missing. It is now unified in the `.filenignore` setting. We will add a UI for (de-)selecting files and directories soon (like on the old client).

**Comment by godzfire** [comment]
Is there an ETA on when that control can get implemented?
