### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by Eggroley** [FilenCloudDienste/filen-desktop#81]
Copied from a previous [issue](https://github.com/FilenCloudDienste/filen-desktop-legacy/issues/9)

"Flatpak support would enable automatic updates, live updates, delta updates, and dependencies decoupling across different Linux distributions."

Is this at all planned or is it something you're not pursuing?

**Comment by aednichols** [comment]
> Flatpak and other software distribution applications will also follow as soon as the desktop client is as good as fully developed with all currently missing features and functions. The same applies to F-Droid for the mobile app. We have not forgotten these options, but for the time being we are using the capacities for the official app/play stores and operating systems that are used considerably more.

https://filen.io/knowledgebase

**Comment by uncharted-user** [comment]
> > Flatpak and other software distribution applications will also follow as soon as the desktop client is as good as fully developed with all currently missing features and functions. The same applies to F-Droid for the mobile app. We have not forgotten these options, but for the time being we are using the capacities for the official app/play stores and operating systems that are used considerably more.
> 
> https://filen.io/knowledgebase

That's amazing!

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io

**Comment by RasheedAZ** [comment]
Just adding here that the current options, deb and appimage do not work on Alpine Linux or postmarketOS which I'm using on my mobile. I have a paid account and have been asking for cross-distro flatpak packaging from the beginning.
