### ISSUE TITLE
Filen Linux App blocking sleep and screen locking

### ISSUE THREAD

**Issue by cwmke** [FilenCloudDienste/filen-desktop#82]
Not really sure what would be causing this. I'm using Plasma Wayland with Filen v2.0.4 and there is a notice in the 'Battery and Brightness' widget that says the below. Any idea what would cause that to happen?

> Filen is currently blocking sleep and screen locking (Electron)

**Comment by juvenoo** [comment]
This happens on Windows and my Archlinux KDE install. There needs to be an option to stop this app from blocking sleep. I don't want my computers to be fully powered up 24/7.

**Comment by Dwynr** [comment]
PowerSaveBlocker has been removed in the latest version. Should be fixed.
