### ISSUE TITLE
Sync location refused on immutable distros

### ISSUE THREAD

**Issue by adurier** [FilenCloudDienste/filen-desktop#82]
On some immutable distros, such as Fedora Silverblue, the home folder is not located in /home but in /var/home. This causes the app to refuse the creation of any sync with the error 'Sync location is not supported'.

**To Reproduce**
1. Go to 'New Sync' in the linux desktop app
2. Try to create a sync between 'Documents' and any cloud folder
3. See error

**Expected behavior**
Accept /var/home/user/* as a correct sync location. Or replace home folder by ~/... (instead of /home/user/...) 

**Screenshots**
![Screenshot From 2024-11-18 04-58-20](https://github.com/user-attachments/assets/355e4421-6f44-474b-a068-2a87d16d8e07)

**OS & version**
 - OS: Fedora Silverblue, Bluefin
 - Filen Desktop v3.0.32

**Comment by anxshi** [comment]
I have the same issue here. It happened to me after switching from version 2.x (AppImage) to 3.0.34 (rpm).

**Comment by ai-idt** [comment]
I encounter the same problem. Is there a download link for a working 2.x version as a temporary workaround? Thanks!

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-web/commit/0ee9086b7706c165f8736ca09417dea87357451f
https://github.com/FilenCloudDienste/filen-desktop/commit/213e2cd466a1bba5f4f7f0ef8b7abd5b0321b772
