### ISSUE TITLE
Minimize to tray for Linux

### ISSUE THREAD

**Issue by TonieStark** [FilenCloudDienste/filen-desktop#83]
**Is your feature request related to a problem? Please describe.**
It was possible to minimize to tray with the previous version of the desktop/sync client.

**Describe the solution you'd like**
Be able to minimize the application  to tray and keep sync in background.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hekel1989** [comment]
+1, came here to create the exact same report. if I click on X, it kills the app, rather than minimising to tray. Please can we have minimise back?

**Comment by RodsonMatos** [comment]
It was the first thing I notice after updating. I closed the window and killed the app.

**Comment by uncharted-user** [comment]
App image for Linux is working for gnome (at least) but there is no minimize to tray on Windows. I was surprised to see such a basic feature is missing!

**Comment by Dwynr** [comment]
We will try to add "minimize to tray" (just like on the windows version) to linux in the next update.

**Comment by paololunghi** [comment]
> As a workaround for now, you can use the `--hidden` flag at startup, but you can't unhide it without restarting the application.

Thank you for the suggestion.
For me (Ubuntu 20.24 w/ gnome) a double click on the tray icon make the window unhide. But then I don't know how to hide it again.

**Comment by Hekel1989** [comment]
> We will try to add "minimize to tray" (just like on the windows version) to linux in the next update.

Thanks.
Do you have an ETA for this please?

This sounds more like a hot fix rather than something to address with a major update. 

It should be a fairly simple fix, but as it stands, it's quite impactful (being able to minimise and open as minimised is taken for granted for any modern application).

Thanks!

**Comment by ahmuro** [comment]
> I would like to see Close To Tray over Minimize to Tray.
> 
> When clicking the close button, it will close the app to the tray. When you minimize the app, it will minimize the app to the taskbar
> 
> Would like to see this on Linux, MacOS and Windows which was the functionality of the Filen Desktop Sync app before this recent overhaul
> 
> Would also like to see an option to launch the app minimized to the tray since I always like to have the app get launched when I boot up my computer

As for my preference and workflow, I think this is the best behavior. Ideally the app should never be closed, the whole point is to keep my stuff in sync when it happens. When I log into my system, the app should be able to autostart without a window, in the tray. And from there I should be able to open it when it needs, minimize it to the dock or task bar or dash, or close it to background. Obviously there should be an option to completely close it but should not be the default behavior.

**Comment by Dwynr** [comment]
Ref:

https://github.com/FilenCloudDienste/filen-web/commit/116e946c5a204faa3f7aa7be00fbe52b0efc35d2
https://github.com/FilenCloudDienste/filen-desktop/commit/2d08ae0cd3bc45cc7777c5eaa5afa3bf5bdc5b69
