### ISSUE TITLE
Network Drive - Not able to use - Loading Forever - Windows 11 on ARM

### ISSUE THREAD

**Issue by yajanbasel** [FilenCloudDienste/filen-desktop#84]
**Describe the bug**

I am not able to use Network Drive in Windows 11 ARM PC.

As shown in below screenshot, whenever I open desktop app and navigate to 'Network Drive' option, it gets stuck on loading screen.
In below screenshot, it has been going on for last 1 hour.

I uninstalled ARM install and installed x86 version and installed it (It runs through windows emulation automatically)
But, x86 install also has same issue, Infinite loading time.

**To Reproduce**
1. Go to Start button / Windows button
2. Click on 'Filen'
3. After software opens, click on the lowest button icon on the left side of the interface. Name of button is 'Mounts'
4. It automatically selects 'Network Drive'. If not, please click on 'Network Drive'
5. See error , enjoy your infinite loading.

**Expected behavior**
- I should be able to use Network Drive. Only way I know is through Desktop app, but it doesn't work.
- Infinite loading shouldn't happen and options inside that 'Network Drive' should be visible. 
- I want to use Network Drive. Please

**Screenshots**
1. 

![image](https://github.com/user-attachments/assets/0935b28c-23ea-43e4-8dc1-caaf2098e782)

2.

![image](https://github.com/user-attachments/assets/b7b53bc2-b5fd-4248-bb43-fab95db96651)

3.

![image](https://github.com/user-attachments/assets/2f33b192-9d6b-426f-a8fe-6ce013bfb221)

**OS (please complete the following information):**
 - OS: Windows 11 on ARM
 - Hardware configuration : 16 GB Ram, 512 GB SSD, Snapdragon X Plus CPU
- Filesystem and Disk type used : SSD, NTFS 

**Additional context**

I downloaded the installer from https://github.com/FilenCloudDienste/filen-desktop/releases/tag/v3.0.32

I downloaded and installed file named "Filen_win_arm64.exe" from https://github.com/FilenCloudDienste/filen-desktop/releases/download/v3.0.32/Filen_win_arm64.exe

I downloaded from github because download link for ARM version of Filen in the website, downloads x86 version and not ARM version.

![image](https://github.com/user-attachments/assets/62d4a636-0fc2-4cb1-afd7-c84d27ad960a)

**Comment by Dwynr** [comment]
We are currently gathering information regarding this issue and will provide a fix asap.

**Comment by Ed-V** [comment]
I am also getting the same issue where it is infinitely loading. No error.

I downloaded the release from the filen.io desktop page. I checked the version it's 3.0.32

![image](https://github.com/user-attachments/assets/75bf27d5-44aa-4d27-980f-162fb6ce7f8c)


![image](https://github.com/user-attachments/assets/4d9a4e18-f43f-4680-9ff8-e4cc18754d03)

**Comment by fazzaan** [comment]
This is still a problem on the x86 version -- I don't have ARM.
There's no other issue on this github repo about this and the OP says it also affected them on x86.

Why was this issue closed as "completed"?
There were no comments and no resolution.

My experience with this:

1. Cannot enable network drive in non-admin mode.
It doesn't request any admin rights when I try to activate it.
![Image](https://github.com/user-attachments/assets/bb947612-c690-4f6c-b14d-320fae246e49)

2. Admin mode:
It can activate the network drive if I start the app as adminstrator -- but a) that is bad practice, and b) it doesn't show up in file explorer anyway, the assigned drive letter is inaccessible.
![Image](https://github.com/user-attachments/assets/5e2687d5-13fa-4269-866f-edacf8f77e16)

I'm on a whistle-stop tour of every available encrypted file storage and I really haven't yet found any that are good enough.
Pr*ton doesn't support Linux (yes, really); Filen supports Linux but the actual _file system integration_ part doesn't even work.
