### ISSUE TITLE
Scoop & Homebrew Packages

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#85]
**Is your feature request related to a problem? Please describe.**
Unable to download app using Scoop or Homebrew

**Describe the solution you'd like**
Releasing and maintaining the app on Scoop and Homebrew

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by uncharted-user** [comment]
+1 for homebrew cask

**Comment by scollovati** [comment]
There is already a cask, but it was outdated and pointing to the old client. I've opened a PR https://github.com/Homebrew/homebrew-cask/pull/192638

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io/
