### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#86]
**Is your feature request related to a problem? Please describe.**
Unable to remain logged into two or more accounts at once

**Describe the solution you'd like**
The ability to be logged into multiple accounts at once, and have background syncing work with all accounts

**Describe alternatives you've considered**
None

**Additional context**
Very useful when you have multiple accounts, such as an account for work and an account for personal use.

To prevent abuse. Add the ability to only be allowed to be logged into paid accounts except for one free account to be logged into.

**Comment by Dwynr** [comment]
Having a "quick account" switch can be useful and is something we might consider in the future, but also background syncing each account at the same time will not be possible by design.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
