### ISSUE TITLE
Lock app with Password

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-desktop#87]
**Is your feature request related to a problem? Please describe.**
Unable to lock app using a password. Limited to a 4 digit PIN

**Describe the solution you'd like**
The ability to lock app using a password

**Describe alternatives you've considered**
None

**Additional context**
Better security to be able to use a password as along as 256 characters

**Comment by uncharted-user** [comment]
Better if there is pass key or fingerprint support.

**Comment by RodsonMatos** [comment]
and also make the password invisible while typing. When I type the pin it is shown the entire time.

**Comment by uncharted-user** [comment]
> and also make the password invisible while typing. When I type the pin it is shown the entire time.

It would have been better to use biometric authentication.

**Comment by nagromc** [comment]
> It would have been better to use biometric authentication.

Or even better, offer the option for the user to choose between:

* password (shorter than the main password/passphrase)
* PIN (not necessarily limited to four digits)
* biometrics / system-wide auth (Windows Hello for instance)

All of these should log out the user after three failed login attempts.

I like how Proton Pass implemented these options:

![image](https://github.com/user-attachments/assets/889b9f29-69a5-4a64-98ea-d53df48f5197)

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
