### ISSUE TITLE
Add an option to limit for number of version to keep.

### ISSUE THREAD

**Issue by uncharted-user** [FilenCloudDienste/filen-desktop#88]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way I can mention how many versions I will need, instead it is keeping either all or none. This is wasting a lot of spaces, whoever don't need that many versions.
**Describe the solution you'd like**
A spin box to increase or decrease from 0 or type the number.
**Describe alternatives you've considered**
Right now, there is no other choice, either in the GUI or CLI.

**Additional context**
This is very important when making backups.

**Comment by nagromc** [comment]
I really like the Syncthing’s approach where the user can choose between [modes](https://docs.syncthing.net/users/versioning.html), particularly, the [_staggered file versioning_](https://docs.syncthing.net/users/versioning.html#staggered-file-versioning).

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io/

**Comment by nagromc** [comment]
This issue has been migrated: https://features.filen.io/posts/95/add-an-option-to-limit-for-number-of-version-to-keep
