### ISSUE TITLE
Odd infos on upload window 

### ISSUE THREAD

**Issue by MazzMat** [FilenCloudDienste/filen-desktop#89]
Using client v2.0.5 on Macbook Pro 14" M1 Pro - Monterey 12.5.1

In the example screenshot 518.2MB/s can't be my upload speed, it's too much!
Could be something related to already uploaded file size?

![upload_screenshot](https://user-images.githubusercontent.com/86950016/191479732-751f0134-e3e4-433d-af72-ade85e0cfd57.png)

**Comment by Dwynr** [comment]
Will be fixed in the next update.
