### ISSUE TITLE
Lacking translations

### ISSUE THREAD

**Issue by mfmw123** [FilenCloudDienste/filen-desktop#91]
Lacking translations:

- The version and sync state when hovering over the Filen icon in the tray.
- "Show", "Upload folders/files", "Settings", "Quit Filen" when right-clicking the Filen icon.
- When hovering over the Filen desktop shortcut the text isn't localised.
- In upload history, dates (minutes, days etc.).

**Comment by lyonelf** [comment]
+1
same thing in web site, plans are not localized.

Possible or too complicated?

**Comment by Dwynr** [comment]
Fixed, can now be translated aswell.

**Comment by lyonelf** [comment]
witch lines?

**Comment by DanielProg39** [comment]
> witch lines?

You can see them [here](https://github.com/FilenCloudDienste/filen-desktop/commit/ec72937b553142edf44e9fe909a6d6ec8d4fd2df#diff-eeba9128bdb5f7987b8d02fc4741a0ece7905f19014ab6042a74040f52f58d79)
