### ISSUE TITLE
Sync status indicator on system tray icon

### ISSUE THREAD

**Issue by paololunghi** [FilenCloudDienste/filen-desktop#91]
**Is your feature request related to a problem? Please describe.**
Currently the only way to check if everything is synced is to open the application window (at least on Linux).
At certain moments (e.g. when I have to turn off the system) is necessary to quickly understand if all the files have finished to sync.

**Describe the solution you'd like**
The status of the syncs should be indicated by changes in the system tray icon.

**Describe alternatives you've considered**
At the moment there's no other option than opening the application window and check.

**Additional context**
None

**Comment by 21Kingshill** [comment]
Agree, since the old quick view on the menu bar icon (MacOS) has gone. Opening the app instead is a step backward

**Comment by uncharted-user** [comment]
Ah! I was wondering why my app image is not syncing. The previous implementation was perfect, but I don't know why devs are removing perfectly working functions and re-adding those after creating an issue!
