### ISSUE TITLE
Sync does not accept "Desktop" as local path

### ISSUE THREAD

**Issue by jonaspoxleitner** [FilenCloudDienste/filen-desktop#92]
**Describe the bug**
It is not possible to select the Desktop on macOS as the local path for syncs.

**To Reproduce**
1. Go to "Syncs"
2. Click on "Create Sync"
3. Fill out all information and use the Desktop (/Users/{user}/Desktop) as the local path
4. See error "The local path you have selected is invalid and cannot be synced. Please choose a different path."

**Expected behavior**
It should be possible to select the Desktop as a local path.

**OS (please complete the following information):**
- OS: macOS 15.1 (24B83)
- Hardware configuration: M1, 16GB, 1TB
- Filesystem and Disk type used: Internal SSD, APFS (Encrypted)

**Additional context**
Selecting the Desktop as a sync location worked before the 3.x.x release.

**Comment by Dwynr** [comment]
Syncing the desktop for macOS is currently not available due to some issues with how macOS stores certain folders on the desktop. We will try to bring it back asap. I will close this issue for now since it's on our internal roadmap anyways.
