### ISSUE TITLE
Allow Users to Choose To Ignore Empty Files or Not

### ISSUE THREAD

**Issue by Ed-V** [FilenCloudDienste/filen-desktop#95]
**Is your feature request related to a problem? Please describe.**

During syncing if a folder I noticed that it was saying it ignored a few empty files. 

**Describe the solution you'd like**
Ability to keep empty files. Can toggle off/on. 

**Describe alternatives you've considered**
None

**Additional context**
This allows the ability to keep the file and folders structure exactly as is. Some work uses them as place holders, flag, etc.

**Comment by Eggroley** [comment]
Sorely needed.

**Comment by rothos** [comment]
Yes. This seems almost like a bug to me. It makes most sense that by default _all_ files, empty or not, are synced. And there can be an option to ignore empty files.

**Comment by devastgh** [comment]
I'm just quietly adding that also empty directories. Not just files.

**Comment by rothos** [comment]
Noting that currently I'm seeing my empty files and directories appear on my Cloud Drive.

**Comment by nickto** [comment]
> Noting that currently I'm seeing my empty files and directories appear on my Cloud Drive.

I only see empty directories, not empty files. Both when using 

- sync and upload in the CLI app (v0.0.23),
- and sync in the desktop app (v3.0.34).

Albeit, only desktop app shows warnings that it has ignored empty files. 

When using drag-and-drop in the browser, empty directories are not synced either (also without warnings).

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io

**Comment by George-TL** [comment]
Latest Desktop App under W10.
Empty directories are not backed-up too.
