### ISSUE TITLE
Add support for JPEG XL

### ISSUE THREAD

**Issue by stephanschindel** [FilenCloudDienste/filen-desktop#96]
**Is your feature request related to a problem? Please describe.**
JPEG XL seems to be one of the upcoming successor of JPEG. It allows to save space in comparison to old JPEG. Many tools already support JPEG XL in the wild.

[JPEG XL](https://jpeg.org/jpegxl/)

**Describe the solution you'd like**
Add support for JPEG XL. In particular: Thumbnail support and opening images.

**Describe alternatives you've considered**
Of course good old JPEG works.

**Additional context**

**Comment by Dwynr** [comment]
https://features.filen.io/posts/2/add-support-for-jpeg-xl
