### ISSUE TITLE
[Feature Request] .docx File Previewing in Webapp

### ISSUE THREAD

**Issue by ghost** [FilenCloudDienste/filen-desktop#97]
Currently, .docx file formats are not supported to preview inside of the web interface, which is quite a problem for some users such as myself who upload tons of documents in the .docx file format and at times need to preview, screenshot, or just check contents of certain files that are .docx. Adding support for .docx file previews would go a long way for usability.

Further, the ability to *edit* .docx files with rich-text formatting would be a massive productivity bonus, if it were possible to implement.

**Comment by Dwynr** [comment]
Not relevant for this repo. Post it into the correct repo (https://github.com/FilenCloudDienste/filen-drive)
