### ISSUE TITLE
Add option for autostart on Linux

### ISSUE THREAD

**Issue by stephanschindel** [FilenCloudDienste/filen-desktop#97]
**Is your feature request related to a problem? Please describe.**
The desktop application on Linux does not autostart nor is there an option to activate autostart.

**Describe the solution you'd like**
Add a setting for autostart to adjust autostart behaviour.

**Describe alternatives you've considered**
The alternative is to start the application manually, but most people do not want that.

**Additional context**
It is fine to add support only for deb and rpm packages. My guess is, that it is more effort to add it for the AppImage version as well.

**Comment by Dwynr** [comment]
This is very tricky and cannot be done 100% reliable due to differences in how Linux DE's behave (and where to store startup entries). For now this is up to the user to configure.

**Comment by Dwynr** [comment]
We now have a dedicated forum for feature requests. Please repost it there if possible! :)

https://features.filen.io
